### ISSUE TITLE
Stage: Hearing date displaying wrong in LUP Portal but correct date displaying in CRM

### ISSUE THREAD

**Issue by gopal2020** [NYCPlanning/labs-zap-search#1000]
Project Name: 52nd Street rezoning

Actual Result: Hearing date displaying wrong in LUP Portal but correct date displaying in CRM
Expected Result: Hearing date should display same  in LUP Portal .

![image](https://user-images.githubusercontent.com/57265341/69454292-da965580-0d33-11ea-9b02-a52de4ed8014.png)

**Comment by allthesignals** [comment]
CRM dates are posted into Postgres as GMT. We'll need to convert either on the frontend or elsewhere.

**Comment by allthesignals** [comment]
I can change the query to convert timezone.

**Comment by hannahkates** [comment]
@allthesignals this issue is connected https://github.com/NYCPlanning/labs-zap-search/issues/984

**Comment by allthesignals** [comment]
A couple options:

 - convert all `timestamp` columns to `timestamptz`, which honors the configured local time, and provides the date with a timezone conversion offset. this will require running the following on the database: ```
SET TIMEZONE 'US/Eastern';
SELECT pg_reload_conf();
SHOW timezone;
```

 - adjust our query to cast the timezones of all relevant columns.

None of it seems to be a good choice. I wonder if there's a way in CRM system to provide data as localized time by default? This would depend on some assumptions about how Skyvia works...

**Comment by allthesignals** [comment]
Have a proposed fix here: https://github.com/NYCPlanning/zap-api/pull/51

**Comment by hannahkates** [comment]
This bug is resolved. QA Team please review.

**Comment by gopal2020** [comment]
This Bug is not fixed. It is still open Issue.
![image](https://user-images.githubusercontent.com/57265341/69758125-ab655700-112c-11ea-8224-dd8643a2681d.png)

**Comment by allthesignals** [comment]
Thanks, looks like our migration step isn't working correctly. 

Fixed for now but will take another look...

**Comment by allthesignals** [comment]
@gopal2020 thanks, I made a silly typo in the migration. please review again. PR for updating migrating coming...

**Comment by hannahkates** [comment]
This is resolved, QA team please check.

**Comment by ksinghprod** [comment]
This issue is fixed now
