### ISSUE TITLE
Duration and days remaining should not be calculated

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-zap-search#1003]
Our app is computing “**x** of **y** days remain” with `.diff(moment(), 'days')` — e.g.: 

```
  @computed('assignment.toReviewMilestonePlannedCompletionDate')
  get timeRemaining() {
    return moment(this.assignment.toReviewMilestonePlannedCompletionDate).diff(moment(), 'days');
  }
```

Unfortunately, this wrong if the review period spans a holiday. CRM has a value for a milestone's duration and logic tat computes a value for days remaining which avoids including holidays. We should pull these values from CRM instead of computing. 

The `dcp_projectmilestones ` table includes two "remaining days" — one of which I assume we should be using for `timeRemaining`: 
- ❌`dcp_remainingplanneddays` 
- ✅`dcp_remainingplanneddayscalculated`

The `dcp_projectmilestones ` table includes a bunch for "duration" ~— not sure which of these we should use~: 
- ❌`dcp_legalduration`
- ❌`dcp_warningduration`
- ❌`dcp_warningduration`
- ❌`dcp_actualduration`
- ✅`dcp_actualdurationasoftoday` <— confirmed below
- ❌`dcp_goalduration`
- ❌`dcp_goalduration2`
- ❌`dcp_goalduration3`

@gopal2020, @Eabrante, @anidamurati, can you please confirm which of these fields we should use?

**Comment by allthesignals** [comment]
Here's a view of those fields

https://dcppfsuat2.crm9.dynamics.com/api/data/v9.1/dcp_projectmilestones?$select=dcp_name,dcp_legalduration,dcp_warningduration,dcp_warningduration,dcp_actualduration,dcp_actualdurationasoftoday,dcp_goalduration,dcp_goalduration2,dcp_goalduration3,dcp_remainingplanneddays,dcp_remainingplanneddayscalculated

**Comment by bean75** [comment]
I would use the actual duration as of today for the duration.
I am not sure which of the remaining planned days is correct as they are not displayed on the milestones.

**Comment by allthesignals** [comment]
`dcp_actualdurationasoftoday` This appears to be it, confirmed by aline and david

**Comment by andycochran** [comment]
Issue updated. Still need to confirm which to use for `timeRemaining`.

**Comment by andycochran** [comment]
A sample of planned days values from the response Matt posted above: 

```
...
"dcp_remainingplanneddays": 153,
"dcp_remainingplanneddayscalculated": 117,
...
"dcp_remainingplanneddays": 174,
"dcp_remainingplanneddayscalculated": 138,
...
"dcp_remainingplanneddays": 17,
"dcp_remainingplanneddayscalculated": -30,
...
"dcp_remainingplanneddays": 17,
"dcp_remainingplanneddayscalculated": -19,
...
"dcp_remainingplanneddays": 284,
"dcp_remainingplanneddayscalculated": 0,
...
"dcp_remainingplanneddays": 21,
"dcp_remainingplanneddayscalculated": 10,
...
"dcp_remainingplanneddays": 5,
"dcp_remainingplanneddayscalculated": -2,
...
"dcp_remainingplanneddays": null,
"dcp_remainingplanneddayscalculated": 59,
...
"dcp_remainingplanneddays": null,
"dcp_remainingplanneddayscalculated": 66,
...
"dcp_remainingplanneddays": 46,
"dcp_remainingplanneddayscalculated": 33,
...
"dcp_remainingplanneddays": 160,
"dcp_remainingplanneddayscalculated": 63,
...
```

IDK if this helps diagnose which we should use, as there seems to be no pattern to which is filled out or which is negative or round, etc.

**Comment by Eabrante** [comment]
@andycochran I will look through an release 1 FDD for the logic associated to the time to complete clock to find out details for the time remaining on a milestone.

**Comment by andycochran** [comment]
Product Partner's best guess is to use `dcp_remainingplanneddayscalculated`. Let's give that a shot and then have folks do some spot checking of the data.

**Comment by ksinghprod** [comment]
There is an open issue on this #1029 
Labs team will monitor this issue
