### ISSUE TITLE
Stage: LUP is getting an error message while trying to log in to the LUP Portal after confirming email

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-zap-search#1008]
Browser: Chrome

Expected Result: LUP should be able to log into the LUP portal after he/she has successfully created an n confirmed his/her account.

Actual Result: Stage: LUP is getting an error message while trying to log in to the LUP Portal after confirming email

![image](https://user-images.githubusercontent.com/57362229/69552270-2a5f6180-0f6c-11ea-8641-643684f6bf33.png)

**Comment by allthesignals** [comment]
Can you try this again? Remember that there's an ETL process that runs for about 5-10 minutes after.

**Comment by allthesignals** [comment]
Actually, I cannot find `komal_singh@aol` in CRM. 

If there is not a Contact komal_singh@aol in the system, it will give that error message.
