### ISSUE TITLE
Stage: Project took 18 minutes to show up in the To Review tab, when the public status changed from filed to certified/refereed 

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-zap-search#1010]
Browser: Chrome
Project Name: Smoketesting 11/08/19
Expected Result: changes from CRM to LUP portal should take about 7-10 minutes to transfer over
Actual Result: Project took 18 minutes to show up in the To Review tab, when the public status changed from filed to certified/refereed 

I had changed the status at 10:57am and it showed up on the LUP portal under the To Review tab around 11:15am (after continuous refreshing and logging in and out)

![image](https://user-images.githubusercontent.com/57362229/69558260-ea04e100-0f75-11ea-8f06-fad5391f08c7.png)

![image](https://user-images.githubusercontent.com/57362229/69558343-056fec00-0f76-11ea-858c-2e4f93397225.png)

AB#52

**Comment by allthesignals** [comment]
Thanks for noting. Not something in our control right now.

**Comment by gopal2020** [comment]
This is working and its taking only 7 minutes.

**Comment by ksinghprod** [comment]
This ETL issue is back, in production this time. Average ETL seems to be ~18-25 minutes from CRM to Portal. 

@gopal2020

**Comment by allthesignals** [comment]
Sorry but this isn't really something we can control without a long term fix. Good to keep a pin in it for later work.
