### ISSUE TITLE
Change dispo submitted by name to say "ZAP LUP Portal"

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#1011]

**Comment by allthesignals** [comment]
Closed by 6a17f0d86aec9fef0f4dc2c3f3555063bf85a1cb

**Comment by hannahkates** [comment]
This bug is resolved. QA Team please review.

**Comment by ksinghprod** [comment]
This issue is now Fixed 

![image](https://user-images.githubusercontent.com/57362229/69657500-518b6100-1048-11ea-81f7-e921704a0220.png)
