### ISSUE TITLE
Stage: LUP portal is not displaying a field error message at the correct place 

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-zap-search#1013]
Browser: Chrome
Project: SmokeTesting 11/08/2019

Expected Result: Out of bound fields should display error message to the user and provide a note to user indicating the correct field limit/instruction 

Actual Result: When Submitting multiple recommendations for a project, for the first recommendation numbers greater than the field limits were entered, the error message displayed on the second recommendation, not the first

![image](https://user-images.githubusercontent.com/57362229/69566073-45d66680-0f84-11ea-950f-9039662cd2e9.png)

**Comment by hannahkates** [comment]
We don't have validation that checks for a maximum allowable value. I think the red highlighting is showing up because those fields still need to be filled in too.

**Comment by ksinghprod** [comment]
there is similar bug open #1019 , if you want you can close this one and just keep the other bug open to track @hannahkates

**Comment by gopal2020** [comment]
This is duplicate bug .
