### ISSUE TITLE
Stage: LUP portal Community board field limits are not constant with the CRM field limits

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-zap-search#1016]
Browser: Chrome

Expected Result: LUP portal Community board field limits should be constant with the CRM field limits

Actual Result: For the following fields: Votes in Favor, Votes Against, Abstain, Total members the field limit is 0-999 on the LUP portal and on the CRM the limits are 0-99

![image](https://user-images.githubusercontent.com/57362229/69568496-b469f300-0f89-11ea-8f60-a93a826764e0.png)

![image](https://user-images.githubusercontent.com/57362229/69568250-3c033200-0f89-11ea-9fb4-0055ab30a09a.png)

**Comment by allthesignals** [comment]
Addressed by https://github.com/NYCPlanning/labs-zap-search/pull/1027

**Comment by allthesignals** [comment]
Please review

**Comment by gopal2020** [comment]
This bug is fixed.

![image](https://user-images.githubusercontent.com/57265341/70065537-4b9dfe80-15b9-11ea-8aa0-06d364daf7cb.png)
