### ISSUE TITLE
Stage: When entering out of bounds numbers for the vote fields, project is not submitting and is there is a continuous loop/buffering 

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-zap-search#1017]
Browser; Chrome

Expected result: If there are fields that contain out of bound numbers, there should be an error message indicating which fields they are prior to submission of a recommendation

Actual Result: When entering out of bounds numbers for the vote fields, project is not submitting and is there is a continuous loop/buffering 

(I send a screen recording to gopal on this issue) 

![image](https://user-images.githubusercontent.com/57362229/69569462-b46af280-0f8b-11ea-8466-7e791774ed1b.png)

**Comment by allthesignals** [comment]
Need a validation

**Comment by allthesignals** [comment]
Addressed by PR #1027 — front end validates the field.

**Comment by hannahkates** [comment]
This is resolved, QA team please check.

**Comment by ksinghprod** [comment]
@andycochran @hannahkates 

same issue as #973 

![image](https://user-images.githubusercontent.com/57362229/69997939-47270680-1523-11ea-8da8-fef9e6ef27ea.png)

**Comment by ksinghprod** [comment]
Matt here:

The issue here is with error handling. After an error, it should allow subsequent tries.

**Comment by allthesignals** [comment]
PR up

**Comment by allthesignals** [comment]
@ksinghprod please retest in about 10-15 minutes from now.

**Comment by gopal2020** [comment]
This bug is fixed
![image](https://user-images.githubusercontent.com/57265341/70178994-36a19800-16ab-11ea-9873-e3eeb726abbc.png)
