### ISSUE TITLE
Stage: When Selecting a community board recommendation outcome, fields are getting validated when selecting the disapproved or Received after clock Expired option

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-zap-search#1019]
Browser: Chrome

Expected Result: When LUP user selects disapproved or Received after clock expired nothing should happen. Only the selected choice should appear (vote fields should not get validated)

Actual Result: When Selecting a community board recommendation outcome, fields are getting validated when selecting the disapproved or Received after clock Expired option

![image](https://user-images.githubusercontent.com/57362229/69574375-f5680480-0f95-11ea-935d-c52847926b10.png)

**Comment by trbmcginnis** [comment]
Looks like this is a recommendation code issue where there are certain codes (e.g. `717170002`) that mean different recommendation labels (e.g. 'Disapproved') for different participant types (e.g. 'Community Board' vs. 'Borough Board'). There's an action in `add.js` that does not specify that each of these different codes might mean something different for different participant types. Fixing now.

**Comment by ksinghprod** [comment]
This issue is now fixed
