### ISSUE TITLE
Talk to Planners: What info should go along with list of project items on Filter View?

### ISSUE THREAD

**Issue by trbmcginnis** [NYCPlanning/labs-zap-search#102]
1. ULURP and non-ULURP numbers (much more important than PAS number/project id)
2. How many actions/which actions associated with project
3. Project description (first 120 characters) 
4. Location information (borough acronym in corner of associated symbol?)
5. Hover over project list item and it highlights location on map

**Comment by chriswhong** [comment]
Closing, this has been prototyped
