### ISSUE TITLE
Stage: LUP User is unable to submit a hearing with multiple hearing

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-zap-search#1020]
Browser: Chrome

Expected Result: LUP user should be able to submit a public hearing consisting of multiple hearings, when selecting submitting each one manually 

Actual Result: LUP User is getting an "Oops something went wrong, can you try again?" message

Seems like the app is in crash state after the error response 

(This time in entered everything correctly)

![image](https://user-images.githubusercontent.com/57362229/69576112-a9b75a00-0f99-11ea-9193-eac2aaa2802f.png)

**Comment by allthesignals** [comment]
This seems old...

**Comment by allthesignals** [comment]
Need to be able to re-submit after error state

**Comment by hannahkates** [comment]
It is possible to submit multiple hearings, but periodically an error blocks this from completing. We've opened a separate issue #1057 focused on this error problem.

**Comment by gopal2020** [comment]
This bug is fixed.

![image](https://user-images.githubusercontent.com/57265341/70340670-388c6800-181f-11ea-897b-d269f650fb32.png)
