### ISSUE TITLE
Stage: Community Board and Borough President are displaying the same hearing information

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-zap-search#1023]
Browser: Chrome
Project: Smoketesting 11/08/2019

Expected Result: Community Board hearings should display only community board hearing information/details and the borough board hearings should only display borough board hearing information/details.

Actual Result: Community Board and Borough President are displaying the same hearing information

![image](https://user-images.githubusercontent.com/57362229/69647635-d6ba4a00-1037-11ea-9a57-76060944ff9c.png)

**Comment by allthesignals** [comment]
Addressed by https://github.com/NYCPlanning/labs-zap-search/pull/1028

**Comment by allthesignals** [comment]
Please review

**Comment by allthesignals** [comment]
Related to #1021

**Comment by hannahkates** [comment]
This is resolved, QA team please check.

**Comment by ksinghprod** [comment]
Can not confirm yet because, when I assign the same LUP (komalpreet singh) different roles (BP and CB) the BP's hearing option is not showing up @hannahkates @allthesignals @andycochran

**Comment by hannahkates** [comment]
We've resolved https://github.com/NYCPlanning/labs-zap-search/issues/1036 so this issue should be ready to test now.

**Comment by ksinghprod** [comment]
This issue is now fixed 

![image](https://user-images.githubusercontent.com/57362229/70162804-4a89d180-168c-11ea-91f0-6401272784cf.png)
