### ISSUE TITLE
Confirm calculation of days remaining

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#1029]
Bujji is checking on this for us.

**Comment by allthesignals** [comment]
Bujji said the field is affixed with _calculated.

**Comment by allthesignals** [comment]
dcp_remainingplanneddayscalculated

**Comment by allthesignals** [comment]
Bujji is working on making the field visible. You can still see it through the API: https://dcppfsuat2.crm9.dynamics.com/api/data/v9.1/dcp_projectmilestones(6277ACB4-10D0-E911-A9A5-001DD8308025)

**Comment by allthesignals** [comment]
"It cannot exclude holidays if it falls on a holiday"

**Comment by allthesignals** [comment]
The CRM doesn't calculate this correctly yet but Bujji is working on it! For now, I think we should just display the raw date itself with a disclaimer concerning holidays and weekends. @andycochran thoughts?

**Comment by allthesignals** [comment]
dcp_remainingplanneddayscalculated is the remaining days one used in the project dashboard milestones view

**Comment by allthesignals** [comment]
I think this is already done! Please review
