### ISSUE TITLE
Stage: New public hearings are appearing on the Portal for community board after a borough president is added to the LUP team

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-zap-search#1032]
Browser: Chrome
Project name: Testing R2 as it relates to the dispos 

Expected result: After adding a BP lup team member and changing the visibility to general public only BP dispositions should appear on the LUP portal 

Actual Result: New public hearings are appearing on the Portal for community board after a borough president is added to the LUP team

in the screen shot below, the two public hearings for the community board had been already submitted (by me). however duplicate blank records seem to be created in the system (on the LUP portal side) 

![image](https://user-images.githubusercontent.com/57362229/69985400-10dc8d80-1509-11ea-80ae-dbc934e7c5f9.png)

**Comment by hannahkates** [comment]
@ksinghprod Let's try to reproduce this one together tomorrow. I'm not seeing the problem.

**Comment by hannahkates** [comment]
We've resolved #1036 so this issue should be ready to test now.

**Comment by ksinghprod** [comment]
This issue is fixed
