### ISSUE TITLE
Stage: Text on a public hearing is not Consistent 

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-zap-search#1035]
Browser: Chrome

Expected Result: Date Unknown text and format should be the same

Actual Result: Date Unknown text is not consistent (on the first hearing it says, date unknown and the second hearing it says unknown date in bold) 

please see screenshot below  

![image](https://user-images.githubusercontent.com/57362229/70065270-cd415c80-15b8-11ea-98b0-c7e4a26dbd09.png)

**Comment by hannahkates** [comment]
Updating the label. This is a design change, not a bug.

**Comment by ksinghprod** [comment]
This issue is fixed
