### ISSUE TITLE
Stage: LUP user is not able to submit A Borough President hearing

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-zap-search#1037]
Browser: Chrome
Project name: TESTING R2 AS RELATES TO THE DISPOS

Expected Result: User should be able to submit a public hearing as a Borough president 

LUP user is not able to submit A Borough President hearing

I made a screen recording for this have shared it with @andycochran @hannahkates @allthesignals 

![image](https://user-images.githubusercontent.com/57362229/70070659-f9ada680-15c1-11ea-892b-9c17ba7489f2.png)

![image](https://user-images.githubusercontent.com/57362229/70070685-03cfa500-15c2-11ea-8ae2-654106584806.png)

![image](https://user-images.githubusercontent.com/57362229/70070706-0a5e1c80-15c2-11ea-89e1-4f5a48871179.png)

**Comment by allthesignals** [comment]
Dispositions by Role computed prop is blank. For some reason... Assignemnt role is visible. Dispo role is also visible. Investgiating...

**Comment by allthesignals** [comment]
![image](https://user-images.githubusercontent.com/5004319/70074133-22389f00-15c8-11ea-8582-5fee7b036e35.png)
![image](https://user-images.githubusercontent.com/5004319/70074141-249af900-15c8-11ea-8b18-0eacc1517737.png)

**Comment by allthesignals** [comment]
<img width="1253" alt="Screen Shot 2019-12-03 at 12 26 25 PM" src="https://user-images.githubusercontent.com/5004319/70074150-295fad00-15c8-11ea-8d88-4981e9ca45d5.png">

**Comment by allthesignals** [comment]
<img width="1312" alt="Screen Shot 2019-12-03 at 12 26 21 PM" src="https://user-images.githubusercontent.com/5004319/70074190-32e91500-15c8-11ea-9c25-6b6b128d7d11.png">

**Comment by allthesignals** [comment]
This assignment is returning no related dispositions but still showing that hearing button.

**Comment by hannahkates** [comment]
Solved by https://github.com/NYCPlanning/labs-zap-search/pull/1039. Disposition records must be visible in order for the user to send data to them. QA team please check.

**Comment by ksinghprod** [comment]
This issue is now fixed

![image](https://user-images.githubusercontent.com/57362229/70085636-a5fd8600-15de-11ea-8768-40701968aaea.png)
