### ISSUE TITLE
Primary Contact should not appear on ZAP Search

### ISSUE THREAD

**Issue by bean75** [NYCPlanning/labs-zap-search#1044]
This is not a field that should show on the public ZAP Search, only on the LUP portal.

**Comment by hannahkates** [comment]
Notes in implementation:
The immediate fix would be to hide Primary Contact for all users, but ideally we should figure out how to show it conditionally, so that LUPs will see it on project profiles.

**Comment by bean75** [comment]
Note that for the LUP portal - it would be ideal if they can see the name and contact info for Primary Contact for the purpose of inviting them to public meetings.

**Comment by hannahkates** [comment]
Closing in favor of duplicate #1093
