### ISSUE TITLE
Stage: Changes made on CRM to a public hearing are not showing up on the portal 

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-zap-search#1046]
Browser: Chrome 
Project name: Soho/Noho

Expected Result: Changes made from CRM to a hearing should appear on the LUP portal 

Actual Result: After make a change to a public hearing from CRM (such as Public hearing location) it does not show on the portal. The portal only displays blank hearing dates 

![image](https://user-images.githubusercontent.com/57362229/70161236-bcace700-1689-11ea-8afd-cfb2ecdf2379.png)

**Comment by hannahkates** [comment]
We didn't design the app to do this. We need to confirm if this functionality is desired.

**Comment by ksinghprod** [comment]
![image](https://user-images.githubusercontent.com/57362229/70261421-69599800-1760-11ea-9b04-737c7c8188c2.png)

**Comment by hannahkates** [comment]
QA Team will retest using the process LUR will follow: 
Reactive disposition --> delete all data and make sure status is set to Draft
