### ISSUE TITLE
Disposition data isn't showing up on public profiles

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#1048]
Now that we've promoted develop to master, real projects in production that have real dispositions filled in should be showing the disposition hearing and rec details on the project profile. They're not showing up.

Example: 
https://zap.planning.nyc.gov/projects/P2016Q0306
https://nycdcppfs.crm9.dynamics.com/main.aspx#850422025

#1048, #1045, #987 should all be fixed in coordination.

![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/6e5fe2a1-4310-4616-aab6-e519c76772ea)

**Comment by trbmcginnis** [comment]
Looks like this is being caused by an error with `hearingsSubmitted` on `hearings-list-for-milestones-list` component, which is coming back false when it should be true

**Comment by allthesignals** [comment]
I'll take a look

**Comment by allthesignals** [comment]
It looks like you already have a passing test for this in your branch :O
