### ISSUE TITLE
Stage: Re-activated Dispositions do not appear on the Lup portal 

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-zap-search#1049]
Browser: Chrome
Project: 25-27 Mercer street -74-711

Expected Result: Re-activated Dispositions should appear on the Lup portal in the draft status (as a public hearing) 
Actual Result: Re-activated Dispositions do not appear on the Lup portal 

![image](https://user-images.githubusercontent.com/57362229/70162409-9ab46400-168b-11ea-8c92-c95ea192187a.png)

![image](https://user-images.githubusercontent.com/57362229/70162500-bfa8d700-168b-11ea-9f8e-a863ef7f1d3d.png)

**Comment by hannahkates** [comment]
We didn't design the app to do this. Our understanding was that LUR would make direct edits to the record on behalf of the LUP. We need to confirm if this functionality is desired.

**Comment by ksinghprod** [comment]
![image](https://user-images.githubusercontent.com/57362229/70261400-5c3ca900-1760-11ea-9d6f-0ac21ad6f3a1.png)

**Comment by hannahkates** [comment]
QA Team will retest using the process LUR will follow:
Reactive disposition --> delete all data and make sure status is set to Draft

**Comment by gopal2020** [comment]
It working fine

![image](https://user-images.githubusercontent.com/57265341/70273505-38855d00-1778-11ea-8f29-7a8a88237236.png)

**Comment by ksinghprod** [comment]
This issue is fixed 

![image](https://user-images.githubusercontent.com/57362229/70335553-7dab9c80-1815-11ea-9694-a837ddcf4c78.png)


![image](https://user-images.githubusercontent.com/57362229/70335591-9320c680-1815-11ea-9a94-e25226555ab3.png)
