### ISSUE TITLE
Stage: User not getting any notification before delete document

### ISSUE THREAD

**Issue by gopal2020** [NYCPlanning/labs-zap-search#1054]
Actual Result: User not getting any notification before delete document
Expected Result: User should get  notification before delete document

LAB LUP Portal

![image](https://user-images.githubusercontent.com/57265341/70257317-09f78a00-1758-11ea-8ea6-b2b1774a3f4e.png)

MCS LUP Portal Screenshot

![image](https://user-images.githubusercontent.com/57265341/70257123-bd13b380-1757-11ea-8379-330a2623cde0.png)

**Comment by allthesignals** [comment]
Thanks! This is an enhancement for now. I think we should add this for later.

**Comment by gopal2020** [comment]
Triage: Not  a bug. possible is enhancement if user request us.
