### ISSUE TITLE
Prod: Projects/disposition records are not showing up on the LUP Portal

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-zap-search#1062]
Browser: Chrome
Project Name: LUP Production Smoke Testing

Expected Result: Project/disposition should show up on the LUP portal after an action and LUP member has been added to a project. (visibility is general public on the project record and disposition)

Actual Result: Projects/disposition records are not showing up on the LUP Portal

![image](https://user-images.githubusercontent.com/57362229/70444387-cbb7de80-1a67-11ea-90e7-38ad5bc66398.png)

![image](https://user-images.githubusercontent.com/57362229/70444412-d4101980-1a67-11ea-98bd-4812400b743a.png)

![image](https://user-images.githubusercontent.com/57362229/70444432-dbcfbe00-1a67-11ea-8d82-d02bb5614189.png)

![image](https://user-images.githubusercontent.com/57362229/70444479-ef7b2480-1a67-11ea-942b-174cf9642417.png)

**Comment by hannahkates** [comment]
Closing: The project did show up, but with a much larger delay than expected. Before we begin the Applicant Portal build, we will experiment with other ETL options that will hopefully be faster.

**Comment by ksinghprod** [comment]
This issue is fixed but the estimate ETL seems be ~25 minutes
