### ISSUE TITLE
Prod: User getting Opps! Error (No Access token present) when refreshing page multiple time

### ISSUE THREAD

**Issue by gopal2020** [NYCPlanning/labs-zap-search#1063]
Actual Result: User getting Opps! Error (No Access token present) when refreshing page multiple time
Expected Result: User should able to refreshing page multiple time.

![image](https://user-images.githubusercontent.com/57265341/70447593-f5bfcf80-1a6c-11ea-9eb6-ebf7b704ab20.png)

**Comment by ksinghprod** [comment]
This issue is fixed @hannahkates
