### ISSUE TITLE
Prod: User not able to submit Hearing date, getting error Notification.

### ISSUE THREAD

**Issue by gopal2020** [NYCPlanning/labs-zap-search#1064]
Actual: User not able to submit Hearing date, getting error Notification.
Expected Result: User should  able to submit Hearing date without any Notification

![image](https://user-images.githubusercontent.com/57265341/70447784-55b67600-1a6d-11ea-8e84-b449793726f2.png)

**Comment by hannahkates** [comment]
Fixed now. This was a problem with the API configuration which has now been resolved.

**Comment by gopal2020** [comment]
Its fixed .
