### ISSUE TITLE
Prod: Date of Public Hearing is not consistent with CRM and LUP Portal

### ISSUE THREAD

**Issue by gopal2020** [NYCPlanning/labs-zap-search#1065]
Actual Result: Prod: Date of Public Hearing is not consistent with CRM and LUP Portal

Expected Result: Prod: Date of Public Hearing is should consistent with CRM and LUP Portal

![image](https://user-images.githubusercontent.com/57265341/70452413-1429c900-1a75-11ea-8ac9-fce6c18af1a5.png)

**Comment by ksinghprod** [comment]
![image](https://user-images.githubusercontent.com/57362229/70461889-b2268f00-1a87-11ea-9cac-59276fc9544b.png)

**Comment by allthesignals** [comment]
Can we try again?

We need explicit migrations for these. I'm concerned that there could be data loss when committing to a non-timezone converted field.

**Comment by hannahkates** [comment]
Resolved now per @allthesignals

**Comment by ksinghprod** [comment]
This is issue is now fixed

![image](https://user-images.githubusercontent.com/57362229/70562739-fa62b180-1b5a-11ea-8d35-a0ea2c2e4fcc.png)
