### ISSUE TITLE
Prod: Date of Vote and Vote Location is not transferring to CRM from the LUP portal on the Borough Board Recommendation 

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-zap-search#1069]
Browser: Chrome
Project Name: LUP Production Smoke testing 12/09/2019

Expected Result: All fields that were entered from the LUP portal should transfer over to CRM on the borough board recommendation 

Actual Result: Date of Vote and Vote Location is not transferring to CRM from the LUP portal on the Borough Board Recommendation 

![image](https://user-images.githubusercontent.com/57362229/70462189-5e687580-1a88-11ea-84ba-ba0f65c5da7b.png)

![image](https://user-images.githubusercontent.com/57362229/70462672-64128b00-1a89-11ea-8acf-c19db63ac31f.png)

**Comment by allthesignals** [comment]
I think I need more information... let's look this afternoon? That GET request error happens when you try to refresh the page to a specific assignment. My guess is that when you recreated this, you did a hard refresh while already on a recommendation. The app then should have redirected you back to `my-projects`. You then clicked recommendation and started filling out again. Thoughts? @ksinghprod

**Comment by ksinghprod** [comment]
Hi Matt, you can stop by our desk anytime, we can try to repro and find the problem

**Comment by allthesignals** [comment]
@ksinghprod sounds good!

**Comment by allthesignals** [comment]
Here's the HAR log of data being sent to the server: 
[dispositions.zap.planning.nyc.gov.har.zip](https://github.com/NYCPlanning/labs-zap-search/files/3946019/dispositions.zap.planning.nyc.gov.har.zip)

Not really seeing any discrepancies, but we really need our FE to probably explicitly note the timezone offset.

**Comment by allthesignals** [comment]
Unable to reproduce myself. Will work with Komal this afternoon!

**Comment by allthesignals** [comment]
@ksinghprod can you set up another to-review assignment for this?

**Comment by allthesignals** [comment]
We tested it and it doesn't appear that the fields get updated when filling otu the form...

**Comment by allthesignals** [comment]
Alright, so this is an "every action" mode with some "all actions" available...
