### ISSUE TITLE
sub-milestone votes should only require recommendation field to show

### ISSUE THREAD

**Issue by trbmcginnis** [NYCPlanning/labs-zap-search#1079]
Currently we are requiring there be 5 fields for community boards and borough boards in order to display the **vote** sub-milestones -- these are `dcpDateofvote`, votes in favor, votes against, votes abstaining, and one of the recommendation fields. For borough presidents we required 2 fields, `dcpDaterecieved` and `dcpBoroughpresidentrecommendation`. 

If there is only a recommendation field present, this will still be useful to show even if there is no other vote information available. Therefore, instead of requiring ALL of the fields to be present, we should just require the recommendation field in order to show the vote sub-milestone.

**Comment by hannahkates** [comment]
Implemented now
