### ISSUE TITLE
Hearing information is breaking the page alignment 

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-zap-search#1081]
Browser: Chrome
Project: Soho/noho

The title of the hearing is going out of the alignment 

![image](https://user-images.githubusercontent.com/57362229/70833538-0bfbc180-1dc6-11ea-90ff-ec342325f0e1.png)

**Comment by allthesignals** [comment]
@andycochran you're assigned on this one — do you want someone else to take care of it?

**Comment by ksinghprod** [comment]
This Issue is now fixed 

![image](https://user-images.githubusercontent.com/57362229/77931271-f8dc0700-7279-11ea-94df-91a140ae6d93.png)
