### ISSUE TITLE
Ordering of search results

### ISSUE THREAD

**Issue by zpaulpower** [NYCPlanning/labs-zap-search#1091]
Hello @hannahkates,

While searching for an active project (Zoning for Transit Accessibility) I didn't have the project title, just the word "transit" (see " *transit" in the search field).

The results under the "Projects" column included active, complete, withdrawn, on-hold and record closed projects, but their ordering was difficult to discern: the active project I was looking for (P2020Y0194) was sandwiched between projects labeled "complete":
![image](https://user-images.githubusercontent.com/40032623/72273821-0c6fbe00-35f9-11ea-9290-83c7ffedd65f.png)

Is there any way of shunting/grouping all the projects labeled "complete", "withdrawn", "on-hold" and "record closed" away from projects labeled "active"?

Thanks,

PHP

P.S. What's the distinction between "complete" and "record closed"? They seem to be indicating the same thing....

**Comment by hannahkates** [comment]
Hi @zpaulpower this is the Microsoft system, so Labs doesn't have any control over it. We're only responsible for what you see at zap.planning.nyc.gov. I think your best bet is to email ZAP_Feedback_DL@planning.nyc.gov with your question.
