### ISSUE TITLE
ZAP_Public_Portal: Co-applicant is missing from the applicant team

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-zap-search#1092]
Browser: Chrome 
Project Name: Industry City Land Use Actions

Expected Result: Applicant team on the Zap Public Portal should contain the co-applicant 
Actual Result: Co-Applicant is missing from the Applicant team 

![image](https://user-images.githubusercontent.com/57362229/72562436-726a7880-3879-11ea-81f4-e67a0031037d.png)

**Comment by andycochran** [comment]
I assume the data has a role but not a name. This is related to #1093; they should be resolved together.

**Comment by hannahkates** [comment]
This PR will fix it. The name was missing because it was being grabbed from the wrong column. https://github.com/NYCPlanning/zap-api/pull/70

**Comment by ksinghprod** [comment]
Is it ready for retest?
