### ISSUE TITLE
FE: Update project status options, add "Prefiled"

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#1095]
ADO issue: https://dcp-paperless.visualstudio.com/dcp-paperless-dynamics/_queries/edit/10106/?triage=true

The new set of project status options (dcp_projectstatus on the dcp_project table) will be the following:
- null
- Prefiled (new status needed per City Charter change)
- Filed (remains unchanged)
- In Public Review (previously "Certified/Referred")
- Completed (previously "Approved", "Withdrawn/Terminated/Disapproved", and "Disapproved")

**Front end work:**
- [ ] Identify all places in the front-end that reference project status and see if any of them need to be updated. Ex: The LUP archive tab includes status options that will no longer exist.
- [ ] Add a filter option for "Prefiled"
- [ ] Add a color display option for "Prefiled"

**Back end work:** https://app.zenhub.com/workspaces/zap-5ca2355cd9fcf5278d715938/issues/nycplanning/zap-api/42

**Comment by allthesignals** [comment]
"Prefiled" also has its own integer code because it's an enum type

**Comment by allthesignals** [comment]
Closing because the main issue is covered in #42
