### ISSUE TITLE
Clean up Skyvia

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zap-search#1117]
@allthesignals commented on [Wed Feb 26 2020](https://github.com/NYCPlanning/labs-infrastructure/issues/68)

<img width="245" alt="Screen Shot 2020-02-26 at 12 50 45 PM" src="https://user-images.githubusercontent.com/5004319/75372582-c1eb8d80-5896-11ea-8de7-879b1e7d179d.png">

We have a bunch of unused integrations in Skyvia. We should clean this up.

**Comment by rtblair** [comment]
Closing as we no longer use SkyVia
