### ISSUE TITLE
Can we avoid ETL timeouts trying to connect to PSQL database?

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zap-search#1132]
@hannahkates commented on [Mon Sep 30 2019](https://github.com/NYCPlanning/labs-zap-api/issues/215)

Periodically, the skyvia ETLs fail because they can't connect to our PSQL database. Can we find a way to avoid this?

![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/053d0903-42b7-4a78-ab27-75ab5158e48e)

**Comment by hannahkates** [comment]
Closing, no more ETLs!
