### ISSUE TITLE
ZAP_Search: Number of projects for each filter on Zap Search do not match the number of projects on CRM

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-zap-search#1150]
Browser: Chrome

ZAP Search project numbers do not match with projects from CRM

For default filter,  
         **Filed, In Public Review:** Zap search displays: 264 Projects
                                        CRM Advance find displays: 294 Projects

![image](https://user-images.githubusercontent.com/57362229/75559076-d5baff00-5a10-11ea-88d7-4b951220968a.png)
 
![image](https://user-images.githubusercontent.com/57362229/75559176-000cbc80-5a11-11ea-978a-b54abd12c460.png)

![image](https://user-images.githubusercontent.com/57362229/75559203-0b5fe800-5a11-11ea-996d-eda3a4a90f8e.png)

           **Filed** ZAP Search displays: 206 Projects
              CRM Advance Find displays: 232 Projects

![image](https://user-images.githubusercontent.com/57362229/75559737-f8014c80-5a11-11ea-90a4-fb10f86aeae2.png)

![image](https://user-images.githubusercontent.com/57362229/75559810-1ff0b000-5a12-11ea-8ce7-875053316e72.png)

![image](https://user-images.githubusercontent.com/57362229/75559759-02bbe180-5a12-11ea-9a5d-ae568899e738.png)

             
**In Public Review**: ZAP Search displays 57 projects
                                  CRM Advance find displays: 65 Projects

![image](https://user-images.githubusercontent.com/57362229/75560075-8c6baf00-5a12-11ea-9292-67b98fa172fd.png)

![image](https://user-images.githubusercontent.com/57362229/75560114-98f00780-5a12-11ea-9675-ebc3f3d9dcc0.png)

![image](https://user-images.githubusercontent.com/57362229/75560149-a4433300-5a12-11ea-8773-84d0f5e4020f.png)

        **Completed**: ZAP search displays: 28,681 Projects
                     CRM Advance Find displays: 31,482 Projects

![image](https://user-images.githubusercontent.com/57362229/75560556-61ce2600-5a13-11ea-8760-449a84dfcad7.png)

![image](https://user-images.githubusercontent.com/57362229/75560590-74485f80-5a13-11ea-963f-7c74851ce337.png)

**Comment by ksinghprod** [comment]
Hi @hannahkates, 

I added the general public clause on CRM, the results still do not match, please see below screenshots 


![image](https://user-images.githubusercontent.com/57362229/75701662-26855e80-5c82-11ea-8c44-3ac49d6e2f9d.png)


//

![image](https://user-images.githubusercontent.com/57362229/75702037-bfb47500-5c82-11ea-8cc5-823608f10a8f.png)




//


![image](https://user-images.githubusercontent.com/57362229/75701957-a6abc400-5c82-11ea-9b25-3c959b2b78a2.png)

**Comment by hannahkates** [comment]
@ksinghprod I think the problem for #1150 and #1152 is that you also need to apply the filter of project visibility, where the projects needs to be set to "General Public"

**Comment by rtblair** [comment]
Blocked by #1159

**Comment by ksinghprod** [comment]
This issue is now fixed 

![image](https://user-images.githubusercontent.com/57362229/78380144-68673480-75a1-11ea-8463-4f7698129518.png)

![image](https://user-images.githubusercontent.com/57362229/78380604-1d99ec80-75a2-11ea-82fe-0603d0036575.png)
