### ISSUE TITLE
Staging LUP Portal: Hearings/Project Dispositions are not displaying on the LUP portal 

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-zap-search#1151]
Browser: Chrome 

Environment: UAT2 & LUP Portal staging 

Project ID: 2018K0500 (9114 5th Avenue Rezoning) 
                  2018M0495 (520 West 183rd Street)

Expected Result: Project Dispositions should show up on the LUP Portal when the project the visibility for the project and project disposition is general public or LUP and the correct milestone is in progress (i.e: Community Board)

Actual Result: Project dispositions/ hearings are not showing up on the LUP Portal 

![image](https://user-images.githubusercontent.com/57362229/75561103-7363fd80-5a14-11ea-85bf-7b8e720ab8fa.png)

![image](https://user-images.githubusercontent.com/57362229/75561749-84613e80-5a15-11ea-90c2-e24405f8ca62.png)
![image](https://user-images.githubusercontent.com/57362229/75561812-980ca500-5a15-11ea-967a-edb9fc31910e.png)

Second Project: 

![image](https://user-images.githubusercontent.com/57362229/75561876-b2df1980-5a15-11ea-8431-fbdc8bed4eca.png)

![image](https://user-images.githubusercontent.com/57362229/75561956-d4d89c00-5a15-11ea-90af-979733edf28c.png)

![image](https://user-images.githubusercontent.com/57362229/75561978-dd30d700-5a15-11ea-9400-219005ef0a3d.png)

![image](https://user-images.githubusercontent.com/57362229/75562110-0f423900-5a16-11ea-88b8-a60d837c9eb3.png)

**Comment by hannahkates** [comment]
@ksinghprod We realized the ETL from UAT2 into our staging database had been frozen since our infrastructure troubleshooting last week. Apologies for that oversight - it's turned back on now

9114 5th Avenue Rezoning is now showing up on "To Review".

520 West 183rd Street isn't showing up because the project visibility is set to "LUP" instead of "General Public". I will confirm the preferred logic for this filtering in backlog grooming tomorrow.

**Comment by ksinghprod** [comment]
Hi @hannahkates, 

Is the ETL running right now? I performed the same steps for another project and it is not appearing on the LUP portal 

![image](https://user-images.githubusercontent.com/57362229/75990925-a4847800-5ec3-11ea-98d4-1c5ae239df5e.png)


//

![image](https://user-images.githubusercontent.com/57362229/75990956-b108d080-5ec3-11ea-897d-3485907a29f7.png)

//
![image](https://user-images.githubusercontent.com/57362229/75990982-bcf49280-5ec3-11ea-9afe-daa6798a3fcb.png)

//
![image](https://user-images.githubusercontent.com/57362229/75991008-c8e05480-5ec3-11ea-9923-35cebf20f515.png)
//


![image](https://user-images.githubusercontent.com/57362229/75991069-e01f4200-5ec3-11ea-9bd7-093a408960f5.png)

**Comment by ksinghprod** [comment]
Hi Hannah, Just wanted to mention that the ETL is about 15-18 minutes at the moment 

@hannahkates
