### ISSUE TITLE
ZAP_Search: Number of Projects for LD action type on ZAP search, do not match ZAP Data

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-zap-search#1152]
Browser; Chrome 

Actual Result: Number of Projects for LD action type on ZAP search, do not match ZAP Data
ZAP Search displays 10 projects for the LD action, with filed public status
CRM Advance find displays: 11 Projects for the LD action, with filed public status

![image](https://user-images.githubusercontent.com/57362229/75563886-19b20200-5a19-11ea-8cb7-b8ec27596fdf.png)

![image](https://user-images.githubusercontent.com/57362229/75564070-71506d80-5a19-11ea-99cc-1e99ad68f53a.png)

Also, when I downloaded the CSV of the results, there are field values that are displayed as true or false for example, Column H,I,J,K. And the action type column is blank 

![image](https://user-images.githubusercontent.com/57362229/75564196-b1afeb80-5a19-11ea-8935-8715e8287900.png)

![image](https://user-images.githubusercontent.com/57362229/75564217-bd9bad80-5a19-11ea-9e69-8d5a2953a205.png)

**Comment by hannahkates** [comment]
@ksinghprod I think the problem for #1150 and #1152 is that you also need to apply the filter of project visibility, where the projects needs to be set to "General Public"

**Comment by ksinghprod** [comment]
@hannahkates I did, Please see my comment on issue 1150. Maybe there needs to be another clause?

**Comment by rtblair** [comment]
Blocked by #1159

**Comment by ksinghprod** [comment]
The original missing project (606 Neptune ave) is appearing now, this issue is fixed 

![image](https://user-images.githubusercontent.com/57362229/78376082-cdb82700-759b-11ea-8bd8-77b01be33233.png)
