### ISSUE TITLE
Revise LUP tab logic

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#1153]
[AB#10645](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/10645)

Based on conversations with our Product Owner, we need to update the logic used to determine which projects show up on which tabs for LUPs. The preferred logic is captured in the image below. The tab should be determined based on the disposition visibility and status, removing all dependencies on milestone status.

![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/d3d5a6e2-3b03-4ccf-baae-f38fd8d774d9)

**Comment by allthesignals** [comment]
This might be a good time to rewrite LUP portal read queries against the CRM API. I'll get a sense of how long that might take.

**Comment by Eabrante** [comment]
@hannahkates user story has been updated
