### ISSUE TITLE
Update field source for Community Districts

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#1155]
AB#10109
[AB#10649](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/10649)

The Community District data attribute is used to 1) filter projects by CD and 2) to display CDs on a project profile.

Currently we use `dcp_communitydistricts` which is a string field containing 4 digit CD abbreviations delineated with semicolons. Ex: 'BK05;BK16;BK04'

The preferred field in CRM is changing to be `dcp_validatedcommunitydistricts`. The contents of this field are similar but comma separated and 3 digits. K00 (Brooklyn), R00 (SI), X00 (Bronx), M00 (Manhattan), Q00 (Queens). Ex: 'M01,X09,M04,R03,X06'

We need to update our app to:
- [x] Use the new correct field `dcp_validatedcommunitydistricts`
- [x] Use commas as the delimiter
- [x] Update any look ups that were dependent on the two digit borough abbreviations. Ex: BK -> K

**Comment by allthesignals** [comment]
This may be related to the discrepancy here:

<img width="1256" alt="Screen Shot 2020-03-04 at 11 32 01 PM" src="https://user-images.githubusercontent.com/5004319/75948122-96f1d280-5e70-11ea-859c-cdb2d0811af5.png">

For a single BBL, there are so many related community districts. Is that unusual?

**Comment by hannahkates** [comment]
@allthesignals The CD field change hasn't been deployed to production yet. I think this project you shared is a data quality problem, where the multipolygon, BBLs, and addresses are incomplete. Multiple CD across multiple boroughs did review the project. I'll submit a data quality issue.

**Comment by Eabrante** [comment]
@hannahkates user story is updated

**Comment by bean75** [comment]
As an fyi - the data on that project looks good. It is a city wide text amendment and those are the districts with POPS.
