### ISSUE TITLE
Display "Prefiled" projects to LUPs on "Upcoming" tab

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#1158]
[AB#10646](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/10646)

## User Story
LUPs need to be able to see "Prefiled" projects on the "Upcoming" tab so that they can prepare for this before the projects certify. However, "Prefiled" projects are tracked differently in the system and displaying them for LUPs will require a change to the LUP tab logic.

## Unresolved questions
What should the display for these "prefiled" projects look like on the upcoming tab? The current milestone timeline on the far right won't have any activity in it, so maybe some text should be displayed instead. Something along the lines of "This application has not yet been filed."

 ## Logic
In addition to the regular filed projects that are shown on the "Upcoming" tab, we need to include "Prefiled" projects which meet the criteria in the table below.

**In order to link the user to the project, we will need to use the dcp_validatedcommunitydistricts field to create a lookup that uses the contact's fullname**

![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/2d1514c1-738d-41e4-9428-eff658b7fb82)

**Comment by Eabrante** [comment]
@hannahkates user story has been updated

**Comment by andycochran** [comment]
I like the idea of replacing the milestone timeline with a sentence indicating that it's a "pre-filed" project: 

> This application has not yet been filed.

Or maybe: 

> Application expected to be filed within X days.

Let's check with the product owner to confirm what language to use.

**Comment by bean75** [comment]
"Filing expected soon" if it needs to be short or "This application has not yet filed."

**Comment by hannahkates** [comment]
Final logic

![Screen Shot 2020-06-30 at 1.24.42 PM.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/dd692fd4-1aa3-4c65-b705-ad76e7cb138c)
