### ISSUE TITLE
Filter: two-letter action code

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zap-search#118]

**Comment by chriswhong** [comment]
Chips interface:  Add multiple two-letter codes to the filter, show only projects that match all chips

**Comment by allthesignals** [comment]
What is the name of the database column for action code?

**Comment by allthesignals** [comment]
There are other kinds of "actions" mentioned in the other filters - is there a more descriptive term for this? Just "action"?

**Comment by allthesignals** [comment]
Need some help reconciling differences between the tooltip data and the database
