### ISSUE TITLE
Provide guidance around max of 5000 records

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#1182]
- [ ] We can't show an accurate count of the number of records that meet filter criteria. We should update this to say "More than 5000" ![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/6fda4daa-295d-4386-a399-21b15997e8d7)

- [ ] Advise user that they can only download 5000 records. Detect # of records in user's results and give conditional message that they have too many records. The project they want may not be included.

**Comment by allthesignals** [comment]
yeah, i did some research, and there's no way around this short of switching everything to a slow fetchXML query. we could use fetchXML to do more sophisticated batch downloads, though. they are slow but work.

we could also let downloads be powered by the "flaky-ish" ETL, and rely on API for immedaite results.

i would say as long as we explain that "more than 5,000" projects match filters", we're okay — the user might just need to refine their search a little more. that said, they may also be depending on total counts by different filter sets, as you mentioned.

when we consider the tradeoffs, i still think one thing to keep in mind is this is a small price to pay in exchange for guarantee that the data is the latest available, not spotty (missing records), and overall a stabler system to maintain.

**Comment by allthesignals** [comment]
another idea: I would see if running the query through fetchXML and requesting a count would be doable... i would have to rewrite the filter parser, though, I think.... let me do some research.

**Comment by hannahkates** [comment]
Planned approach:
 - Provide friendly message that you can only download 5000 or less
 - Once open data is available, provide link to download everything
 - Reach out users to see how many records they normally download.

**Comment by andycochran** [comment]
Here's a mockup/prototype of this change: 

https://sprout-beech.glitch.me/

![image.png](https://images.zenhubusercontent.com/5ca23880d9fcf5278d71596e/6c65012a-613b-4d10-9d20-c31300030084)

![image.png](https://images.zenhubusercontent.com/5ca23880d9fcf5278d71596e/0390bbd1-473b-4dc8-b017-3df25d94e25a)

**Comment by hannahkates** [comment]
This has already been implemented
