### ISSUE TITLE
Sort order is different

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#1183]
I don't think this is a big deal, but it raises the question once again of what the best sort order would be.

Prod
![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/94c4f882-92b2-4455-9546-99a0d278a1a6)

vs.

New test
![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/c3783a23-b8af-4d12-9b46-b1fdd140897c)

**Comment by allthesignals** [comment]
I'm able to sort on certain columns but i'm not able to change how certain columns order themselves. So, I sort on publicstatus, but that does alphabetical descending. I followed the SQL as closely as possible:

```
ORDER BY lastmilestonedate DESC NULLS LAST,
CASE  WHEN dcp_publicstatus_simp = 'In Public Review' then 1
      WHEN dcp_publicstatus_simp = 'Prefiled' then 2
      WHEN dcp_publicstatus_simp = 'Filed' then 3
      WHEN dcp_publicstatus_simp = 'Completed' then 4
            ELSE 5
        END ASC
```

One way around this is to request a new column that is computed off public status that represents the alphanumeric sort position of that label, public_status_position or something.

**Comment by allthesignals** [comment]
we _might_ be able to use the Odata  `$computed` param for this
