### ISSUE TITLE
Filter counts are different when filtering by CD

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#1184]
We should fix this when we do #1155

**Filter for:**
project community district = ____
AND project visibility = 'General Public'

**Comment by allthesignals** [comment]
I'm not sure why this is. I'm using the dcp_communitydistricts field (I know we're updating that soon). it could be that it's not case insensitive? I'd be interested in seeing which ones are missing.

**Comment by allthesignals** [comment]
This could also be that some records were missed again in the ETL transfer (yikes).

**Comment by hannahkates** [comment]
Suggestion: look into "inactive" CDs

**Comment by hannahkates** [comment]
This should be fixed by #1214 - will check on staging once the PR is merged.
