### ISSUE TITLE
Staging: For Re-activated dispositions, when submitting the public hearing, user is getting an error message 

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-zap-search#1193]
Browser: Chrome
Project Name: Gowanus Neighborhood Plan

Expected Result: After submitting a recommendation once, A CRM LUR user can re-activate the disposition record and a blank hearing should display on the LUP Portal. The LUP User should be able to submit the hearing again. 

Actual Result: User is getting an error message when submitting a a re-activated disposition record/ public hearing 

![image](https://user-images.githubusercontent.com/57362229/77939563-604b8400-7285-11ea-9211-fe1e47c4619b.png)

**Comment by ksinghprod** [comment]
This issue is now fixed, 

![image](https://user-images.githubusercontent.com/57362229/78042761-766a4a80-7340-11ea-82af-f43f82a78ebe.png)

**Comment by hannahkates** [comment]
Thanks for retesting @ksinghprod .
