### ISSUE TITLE
Filter: Free-form Text

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zap-search#120]

**Comment by chriswhong** [comment]
This is filter for free-form text fields:

- Applicant Name
- Project Brief
- Project Name

One search control with a text input can match agains all three fields with each keystroke.  (with debouncing of course)

**Comment by allthesignals** [comment]
@andycochran can you stub in something for this?

**Comment by allthesignals** [comment]
@chriswhong we might also use labs-ember-search and the search-api...
