### ISSUE TITLE
LUP unable to submit hearing on "upcoming" when assigned as both BP and BB

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#1221]
## What should happen
If an LUP user is assigned a BP and BB role on a project, they should be able to submit hearing info from the upcoming tab for each of the roles.

## What's happening instead
The project is showing up twice on the upcoming tab, reflecting the two different roles. However, the hearing button is only enabled for one of the assignment cards. The frontend `dispositionsByRole` attribute is what determines whether the button is enabled. It is null for one of the assignment cards.

Example project: 2021M0102
![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/ebfaa299-4035-4767-9594-9ffa33df88d6)

## Steps to reproduce
1. Find a test project to use. 2021M0102 is a good example.
2. Assign a user to the project LUP team as both a BB role and BP role. singh.komalpreet20%40gmail.com is already assigned this way for 2021M0102
3. View the user's upcoming tab on the LUP dashboard.
4. See that the project assignment is listed twice, but only one of the upcoming hearing buttons are enabled.
5. Use ember data inspector to see that `dispositionsByRole` is null for the assignment card with the disabled button.
6. Deactivate the LUP team member assignment that had the enabled button. Refresh LUP and see that the remaining assignment now contains data for `dispositionsByRole` and the button is enabled.

It seems like something may be wrong with the `dispositionsByRole` computed value in the assignments model. When there are multiple roles on a project for the same user, the app seems to only find disposition data for whichever assignment relationship was created most recently.

**Comment by godfreyyeung** [comment]
This is an amazing issue writeup. Thank you @hannahkates !!!

**Comment by hannahkates** [comment]
Hi @ksinghprod just wanted to make sure you saw this is resolved.

**Comment by ksinghprod** [comment]
Hi Hannah, I thought I closed this, It is working. I re tested it the day you added the resolved label. Ill add a screenshot and close

**Comment by ksinghprod** [comment]
This issue is now fixed 

![image](https://user-images.githubusercontent.com/57362229/88410326-3eca5700-cda4-11ea-904d-c0b8775157c0.png)
