### ISSUE TITLE
The "Name of the Person Completing this form" is not getting populated upon submission of the CB/BB/BP recommendation 

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-zap-search#1222]
Fixes [AB#12122](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12122)

## Browser
Chrome

## Project Name
16th Avenue Rezoning

## Expected Result 
Upon Submission of the CB/BB/BP recommendation the "Name of the Person Completing the Form" field on CRM should get auto populated with "ZAP LUP Portal"

## Actual Result
The "Name of the Person Completing this form" is not getting populated upon submission of the CB/BB/BP recommendation 

![image](https://user-images.githubusercontent.com/57362229/86806796-399ca680-c047-11ea-989e-83ed148a971e.png)

**Comment by hannahkates** [comment]
This is in the code already, but apparently it isn't working correctly. https://github.com/NYCPlanning/labs-zap-search/blob/develop/client/app/models/disposition.js#L67

**Comment by hannahkates** [comment]
Duplicate of #1199.

**Comment by ksinghprod** [comment]
This issue is fixed, closed ADO bug https://dcp-paperless.visualstudio.com/ZAP%20Portals/_workitems/edit/12122
