### ISSUE TITLE
The "To Review Tab" is displaying hearings&recommendations without the LUP Disposition visibility are being general public/LUP

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-zap-search#1223]
## Project Name
16th Avenue Rezoning 
2019K0024

## Expected Result:

![image](https://user-images.githubusercontent.com/57362229/86812646-3c01ff00-c04d-11ea-92a7-fe58e9318c2f.png)

## Actual Result: 

![image](https://user-images.githubusercontent.com/57362229/86812698-4ae8b180-c04d-11ea-9e29-77d8b1ecd71d.png)

![image](https://user-images.githubusercontent.com/57362229/86812853-79ff2300-c04d-11ea-927f-2ce4106d7848.png)

**Comment by ksinghprod** [comment]
The same is happening for the "Reviewed Tab"

**Comment by hannahkates** [comment]
Will be fixed by #1224

**Comment by ksinghprod** [comment]
@hannahkates

 This issue is not fixed, my project that has Internal DCP only Visibility displayed in the "to be reviewed" tab. (with the disposition's visibility being general public)  

![image.png](https://images.zenhubusercontent.com/5ddc41dcbf921600010fc58b/2761c2ca-c6e9-4385-aeeb-7889210a8d23)

![image.png](https://images.zenhubusercontent.com/5ddc41dcbf921600010fc58b/6393d14d-bacd-4e57-a1e9-56c970a45fc9)

![image.png](https://images.zenhubusercontent.com/5ddc41dcbf921600010fc58b/38e4c823-1032-4d61-9e3a-f9729be30a21)

**Comment by ksinghprod** [comment]
This issue is now fixed 

![image](https://user-images.githubusercontent.com/57362229/88410960-1a22af00-cda5-11ea-87b6-7d0292c8182b.png)


![image](https://user-images.githubusercontent.com/57362229/88410939-1131dd80-cda5-11ea-8e7c-ad1639a547c8.png)


![image](https://user-images.githubusercontent.com/57362229/88410986-29096180-cda5-11ea-890b-28a914c447d6.png)




![image](https://user-images.githubusercontent.com/57362229/88411020-3aeb0480-cda5-11ea-8e30-ffb97e9a3ec5.png)
