### ISSUE TITLE
Improve Display names for Milestones

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zap-search#126]

**Comment by chriswhong** [comment]
Work with Linda M. to determine more human-readable .

1	First Draft Plan/Commitment Strategy/ Proposal
1	Interdivisional Meeting Prep
1	1st Draft Zoning Proposal
1	Interagency Launch*
1	CPC Public Meeting - Vote
1	Prepare and Review PDEIS Chapters
1	EIS Public Scoping Meeting
1	Headquarters - Pre-Hearing Review / Post Referral
1	Post Cert Preparation (Dockets and NOC)
1	EIS Draft Scope Review
1	DEIS Public Hearing Held
1	Scoping Hearing*
1	Project Completed
1	Land Use Draft Application Submitted Review
1	LU Application Complete
1	Review Pre-Application Statement
1	Prepare EIS Draft Scope
1	Filed EAS Review
1	Borough Board Referral
1	DCP Internal Commitment
1	Land Use Fee Payment
1	Prepare Filed EAS
1	Project Readiness
1	RWCDS Sign-off*
1	Prepare Filed Land Use Application
1	Draft EAS Review
1	Commence Drafting of LU Application
1	Finalize Actions
1	Final Letter Sent
1	CPC Deadline
1	Interdivisional Meeting/Sharing*
1	CEQR Fee Payment
1	Headquarters - Pre-Certification
1	2nd Draft Zoning Proposal/Commence drafting RWCDS
1	Prepare Pre-Application Statement
1	Borough President Referral
1	Prepare Reasonable Worst Case Development Scenario Memo
1	Land Use Application Filed Review
1	CEQR Fee Invoice Review
1	Review RWCDS Memo Submitted
1	Migrated Milestone
1	FEIS Submitted and Review
1	NOC of Draft EIS Issued
1	Consultant Schedule Sign-off*
1	Mayoral Veto
1	DEIS Scope of Work Released*
1	Community Board Referral
1	CPC Public Meeting - Public Hearing
1	Final Scope of Work Issued
1	Headquarters - Post Hearing
1	City Council Review
1	Neighborhood Plan/Pre-Cert Commitments/Final Proposal Shared Publicly
1	Prepare Land Use Draft Application
1	Land Use Fee Invoice Review
1	Review Session - Certified / Referred
1	Review Session - Pre-Hearing Review / Post Referral
1	Prepare Draft EAS
1	Review Session - Post Hearing Follow-Up / Future Votes
1	Deliverable Shared Publicly*
1	Project  Created
1	Vetted Planning Framework/Feasibility Study/ Proposal
1	Informational Interest Meeting Prep
1	Public Launch/Announcement*

**Comment by andycochran** [comment]
Calling this done. We can address any specific milestone names in separate issues.
