### ISSUE TITLE
Add ZAP Alerts feature flag to ZAP Search

### ISSUE THREAD

**Issue by TylerMatteo** [NYCPlanning/labs-zap-search#1536]
## Acceptance criteria
- [] A feature flag is created to toggle "New project" feature called `SHOW_ALERTS`
- [] Feature is opt-in (defaults to `false`)
- [] Feature is activated with Environment Variable

Based on feature flag work for Self Service in App portal. See corresponding [issue](https://github.com/NYCPlanning/labs-applicant-portal/issues/1242) and [PR](https://github.com/NYCPlanning/labs-applicant-portal/pull/1261/files#diff-6ee83be565750b9a226713abd37c1a340445e280c8bd60382f9017d4e298d45dR145) for reference.

**Comment by TangoYankee** [comment]
Update PR to reference: https://github.com/NYCPlanning/labs-applicant-portal/pull/1263/files
