### ISSUE TITLE
Confirm Subscriber Endpoint

### ISSUE THREAD

**Issue by TylerMatteo** [NYCPlanning/labs-zap-search#1550]
Create a `PATCH` endpoint in ZAP Search to update subscriber custom properties.

New endpoint should exist as `PATCH` to `/subscribers/<uuid>`. For now, request body should only expect one property that lets us set the user's "confirmed" property to `1`
```
{
    "confirmed": 1
}
```

- [ ] Validate the request body and attempt to update the "confirmed" property for a user to the given value:
- [ ] The UUID in the path params should be used to look up the user based on their `anonymous_id` property in SendGrid

See #1560 for details on what confirmed custom field will be in SendGrid. It should be `zap_staging_confirmed` for staging and `zap_production_confirmed` for production.

**Comment by dhochbaum-dcp** [comment]
Is there a benefit to having user signup confirmation having the same endpoint as updating user subscriptions?

**Comment by TylerMatteo** [comment]
> Is there a benefit to having user signup confirmation having the same endpoint as updating user subscriptions?

Yes - it's a best practice to create endpoints around "resources" (in this case `subscribers`) and the standard HTTP methods (POST, GET, PATCH, etc) whenever possible. Instead of having an endpoint specifically for "confirming" a subscriber, we can have an endpoint for the general task of editing a subscriber's information and it can be used for editing confirmation status as well as subscriptions.
