### ISSUE TITLE
Build project update detect PA flow

### ISSUE THREAD

**Issue by TylerMatteo** [NYCPlanning/labs-zap-search#1554]
Create a Power Automate flow targeting CRM UAT2 that triggers when the following conditions are met:

- [ ] The `dcp_publicstatus` field is changed on a `dcp_project` entity in ZAP (Dynamics CRM) 
- [ ] That project's `dcp_visibility` property is set to `717170003`. This number is the value in CRM corresponding to "General Public" visibility
- [ ] The new `dcp_publicstatus` value is "In Public Review" or "Filed". See [this lookup in ZAP Search code](https://github.com/NYCPlanning/labs-zap-search/blob/develop/server/src/project/project.service.ts#L59) for corresponding values in CRM.

When conditions are met:
- [ ] Call endpoint built in #1555 with correct data and credentials

**Comment by TylerMatteo** [comment]
@pratishta @dhochbaum-dcp The Flow looks good! One change to make:
I think "select rows" should only have `dcp_publicstatus`. That field (confusingly, but the tooltip clears it up) determines what fields trigger an update when changed, not the values we need to pass along to other steps in the flow. We only need to _trigger_ the flow when the public status changes.
<img width="736" alt="Image" src="https://github.com/user-attachments/assets/2d1d8bb3-3d69-4620-8747-8a1b5edb6d32" />

**Comment by pratishta** [comment]
Makes sense, it's been updated.

**Comment by TylerMatteo** [comment]
@pratishta @dhochbaum-dcp Looks good now. Closing to keep this scoped to creating the staging/UAT2 flow. We'll handle the service account and production flow set up in separate issues.
