### ISSUE TITLE
Build endpoint for sending project updates

### ISSUE THREAD

**Issue by TylerMatteo** [NYCPlanning/labs-zap-search#1555]
Build new endpoint to trigger project update emails for given project

- [ ] New `POST` endpoint to `/projects/<projectid>/send-update`
- [ ] Calls Sendgrid APIs to create [single sends](https://www.twilio.com/docs/sendgrid/api-reference/single-sends/create-single-send) for project to correct CD and citywide lists with correct metadata.
- [ ] Endpoint requires `Authorization` header implementing `Basic` authorization method. Credentials should be `username:password` base64 encoded. Username can be `ae-admin`, password should be randomly generated UUID to be stored as environment variable. If given authorization header contains incorrect credentials, return `401 Unauthorized` [response](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401).
- [ ] If single sends are created and scheduled succesfully, return `200`
- [ ] If project with given id not found, return `404`

**Comment by dhochbaum-dcp** [comment]
Notes:
Tyler said: https://docs.nestjs.com/security/authentication#passport-integration
You can use the handlebars package to build the raw HTML and then send that.
