### ISSUE TITLE
Configure custom properties and segments in Sendgrid

### ISSUE THREAD

**Issue by TylerMatteo** [NYCPlanning/labs-zap-search#1560]
Configure necessary custom fields and segments in SendGrid for production and staging environments.

### For staging and production environments, create the following custom fields, using the "number" custom field type
- [x] One for each of the 59 community districts
- [x] One for "citywide"
- [x] One to track whether or not the user has confirmed their subscriptions

### Custom field naming convention
* Naming convention for CD fields should follow this pattern `zap_<environment>_<CD identifier>`. CD identifier should use ZAP CD IDs which ZAP Search already has a copy of [here](https://github.com/NYCPlanning/labs-zap-search/blob/develop/client/app/helpers/lookup-community-district.js) - look at the first item in each of the nested arrays (`K01`, `K02`, etc). For example, the field for `K01` has already been created for staging:![Image](https://github.com/user-attachments/assets/d3262a0a-a6ae-4e91-9903-3dbc3ca3a51c)
* Naming for "citywide" field should be `zap_<environment>_CW`
* Naming for "confirmed" field should be `zap_<environment>_confirmed` 

> Note you should create 122 custom properties total

### For staging and production environments, configure the following segments

- [x] One for each of the 59 community districts
- [x] One for "citywide"

> Note you should have 120 segments total

### Segment naming conventions
* Follow pattern `zap-<environment>-<CD identifier>`. For example, `zap-staging-K01`. For citywide segments, use `CW` for identifier.
* Segments should be associated with the Lists for their environments - (`zap-subscribers-staging` and `zap-subscribers-production`)
* Each segment should have two conditions
    * The custom field for the corresponding identifier is `1`
    * The "confirmed" custom field for the corresponding environment is `1`

**Comment by pratishta** [comment]
@TylerMatteo Added the custom fields and created the segments.
