### ISSUE TITLE
Manage subscriptions front end

### ISSUE THREAD

**Issue by TylerMatteo** [NYCPlanning/labs-zap-search#1595]
Create new page for managing subscriptions, pre-populated with existing user subscriptions:

- [ ] Create new page at route `/subscribers/<id>`
- [ ] Page implements designs found [here](https://www.figma.com/design/1HrOm1tkJ3lowQhrSRkPLs/ZAP-Listserv%3A-Wireframes-and-User-Stories?node-id=678-385&node-type=frame&m=dev)
- [ ] Pre-populate checkboxes by querying for user's current subscriptions using the `id` route param.
- [ ] "Update" button should be disabled until selected subscriptions are different from existing values.

**Comment by pratishta** [comment]
@TylerMatteo  Is sending users to the post-confirmation page part of the work for this ticket? https://www.figma.com/design/1HrOm1tkJ3lowQhrSRkPLs?node-id=678-385&m=dev#1030068624
