### ISSUE TITLE
Create non-DCP Project update email template for Community District subscriptions

### ISSUE THREAD

**Issue by TylerMatteo** [NYCPlanning/labs-zap-search#1596]
Create email template in Sendgrid for project updates for projects where DCP is not the applicant:

- [x] Implement designs in [Figma](https://www.figma.com/design/1HrOm1tkJ3lowQhrSRkPLs/ZAP-Listserv%3A-Wireframes-and-User-Stories?node-id=190-28&node-type=frame&m=dev).
- [x] Project name text should link to page for the project in ZAP Search. Use `https://zap-staging.planninglabs.nyc` or `https://zap.planning.nyc.gov` URL depending on environment.

**Comment by dhochbaum-dcp** [comment]
Link to dynamic template for review: https://mc.sendgrid.com/dynamic-templates/d-feab82e41e834dd891a5b119daf5483b/version/cc922dea-533f-4cf8-8a4e-6eb38530ad72/editor

**Comment by TylerMatteo** [comment]
```
{{#if project.additionalpublicinformation}}
                        <p>New York City Department of City Planning is the applicant. <a href="{{project.additionalpublicinformation}}" target="_blank" rel="noreferrer" style="color: #3E4451;">Click here to learn more.</a></p> 
{{/if}}
```

@dhochbaum-dcp It looks like you're using the same template for DCP and non-DCP projects, which is fine but can you have the template take a boolean defining whether or not DCP is the applicant and use that here instead of relying on the presence of `additionalpublicinformation`? That link can be present for non-DCP projects so I'm concerned using it in this way could be confusing for devs in the future and lead to bugs where we list DCP a the applicant for non-DCP projects.

**Comment by dhochbaum-dcp** [comment]
No problem - this is updated.
