### ISSUE TITLE
Create DCP Project update email template for Community District subscriptions

### ISSUE THREAD

**Issue by TylerMatteo** [NYCPlanning/labs-zap-search#1597]
Create email template in Sendgrid for project updates for projects where DCP is the applicant:

- [x] Implement designs in [Figma](https://www.figma.com/design/1HrOm1tkJ3lowQhrSRkPLs/ZAP-Listserv%3A-Wireframes-and-User-Stories?node-id=190-70&node-type=frame&m=dev).
- [x] Text should be different dependent on new public status being "Filed" or "In Public Review"
- [x] Project name text should link to page for the project in ZAP Search. Use `https://zap-staging.planninglabs.nyc` or `https://zap.planning.nyc.gov` URL depending on environment.
- [x] "Click here to learn more" link will use `dcp_Additionalpublicinformation` field from ZAP. If given value for this field is null, "New York City Department of City Planning is the applicant. Click here to learn more." text should not appear.

**Comment by dhochbaum-dcp** [comment]
Link to dynamic template for review: https://mc.sendgrid.com/dynamic-templates/d-feab82e41e834dd891a5b119daf5483b/version/cc922dea-533f-4cf8-8a4e-6eb38530ad72/editor
