### ISSUE TITLE
If entire result set (project list) has no geometry, map zooms to null

### ISSUE THREAD

**Issue by trbmcginnis** [NYCPlanning/labs-zap-search#160]

**Comment by andycochran** [comment]
@chriswhong  Is this related to #166? Or can they be addressed together?

**Comment by chriswhong** [comment]
166 is already done.  The fix will be similar, another check before applying the `bounds` object in the API response.

**Comment by andycochran** [comment]
If 166 is done, should we close it? 🤷‍♂️
