### ISSUE TITLE
Map Tooltip x and y are relative to the page, not the map; tooltip now falls below map

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zap-search#202]
![screen_shot_2018-07-02_at_11_04_32_am](https://user-images.githubusercontent.com/1833820/42171758-2b97b6ea-7de8-11e8-8778-9033ad5eda50.png)

The tooltip is positioned using the `e.point.{x, y}` in `handleMouseMove()`, but it seems to be positioned based on the page instead of the map container.

**Comment by allthesignals** [comment]
Tooltip now sits below map entirely - needs some attention ASAP

**Comment by andycochran** [comment]
`handleMouseMove()` is not in the codebase.  🤔

**Comment by andycochran** [comment]
"`handleMapMove()`" :)
