### ISSUE TITLE
Change over time time-slider

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zap-search#209]
Want a time slider for projects list map view

**Comment by chriswhong** [comment]
Use a project's certified/referred date to filter.

**Comment by allthesignals** [comment]
> The latest date should be today, not the latest certified/referred date in the database
Do you mean the default should be:
 - Turn on time slider
 - Slider defaults to the minimum being the earliest date of the results, and the maximum being the current date?

**Comment by bean75** [comment]
I think so, JK asked for this at last Check-in I think, wasn’t there so I am not 100% on the purpose
