### ISSUE TITLE
browser compatibility

### ISSUE THREAD

**Issue by bean75** [NYCPlanning/labs-zap-search#222]
Does not appear to load at all in IE and intermittantly in Firefox - just blank screens, no error message.

**Comment by chriswhong** [comment]
Confirmed working in IE11 after adding in the ember babel dependencies. 

 Still need to do some more manual testing in browserstack

**Comment by chriswhong** [comment]
Conducted basic testing in latest Chrome, Firefox, Safari across Mac, Windows, Android, and iOS.  Nothing of concern to report.
