### ISSUE TITLE
Applicant names not appearing

### ISSUE THREAD

**Issue by bean75** [NYCPlanning/labs-zap-search#223]
There are a few records which have "unknown" as the applicant name and yet in ZAP there is applicant information. It could be a data delay issue, but the records I checked have not had that field edited since mid April, so pretty sure it must be something else! Check 1010 Pacific Street or 1501-1555 60th Street projects as examples.

**Comment by allthesignals** [comment]
We're not showing co-applicants. We should include: 
 - contact
 - applicant
 - applicant-team

We'd want to pull both of those roles. Just include first and last names, even for "contacts" where we were concerned about PII.

**Comment by chriswhong** [comment]
Added a CASE to use either `account.name` or `contact.fullname`, or null if the project has neither associated with it.  Unclear on what an applicant-team is or how they fit into this.  Seeking guidance.
