### ISSUE TITLE
Completed milestones not appearing

### ISSUE THREAD

**Issue by bean75** [NYCPlanning/labs-zap-search#225]
Some completed milestones that should be showing are not - 605 Hart for instance is not showing its CPC vote date (or filed application dates etc.): 
![capture](https://user-images.githubusercontent.com/40247515/42239259-e58ff8f4-7ef2-11e8-9c0c-6b18b8791821.PNG)

This seems to be inconsistent - some projects are showing these - others are not?

**Comment by andycochran** [comment]
@chriswhong  This is a result of our logic, which looks for two characters then a dash. So "Ad-hoc" triggers the regex and breaks the `name`.

**Comment by chriswhong** [comment]
![NYC_Planning_-_Zoning_Application_Search_🔊.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/580f65f4e41c721300d753c7/125516c66e82c728ace21e0d46c6adb91cb28fa881e7b64da362bdab1349297a27039c0a6095ef21bc436f08000121cf14091d17a4964984020c2e6c981c49b28b380c30d43703a9ea834ab853bc728f4d8ce0e9824cc0e96e74ef89dc4e360c190acbae0361ffc412820db459eb5f54ac193766e577327c4e951c752f626634e6.png)

As far as I can tell this is not relevant anymore, see attached screenshot... filed dates and CPC vote milestones are showing up for the 605 hart project.

@andycochran we aren't actually regexing these milestone names, we are pulling from a lookup table that doesn't have the prefix and hyphen.

**Comment by bean75** [comment]
Seems to be fixed to me!

**Comment by chriswhong** [comment]
Closing!
