### ISSUE TITLE
Update Mirage with new content

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zap-search#226]
Plz don't let this fall out of sync - need to update with new data expectations:

![Screen Shot 2018-07-03 at 3.03.25 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246454f06b7191a37bf112284f5d5a5ecc3c4a4356bcbbd671f3e57862804e0ebfd0385826c06f15aeb1d44ab701ba21d81e8db4ef8b44d2f42f67b6d5db1063474f4dcbed5727a19041c95df54be74951a2163463e1712431.png)

**Comment by hannahkates** [comment]
Duplicate
