### ISSUE TITLE
Lookup labeling for ULURP, Non-ULURP, etc

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zap-search#244]

**Comment by andycochran** [comment]
Nix the first column. "N" is the prefix of "N160101ZRQ."

**Comment by andycochran** [comment]
Closed by https://github.com/NYCPlanning/labs-zap-search/commit/322b910082f73e5bd02a1127dabe6e7a8f6e8fa4#diff-0cb8ec66fe87f76e5c145e2350cb7610L89
