### ISSUE TITLE
Dummy Data--JSON based on ZAP Project Page

### ISSUE THREAD

**Issue by trbmcginnis** [NYCPlanning/labs-zap-search#25]
- [x] Put together mockup data
 - [ ] Use [fakerjs](https://github.com/marak/Faker.js/) to generate reasonable fake data in Mirage
in https://github.com/NYCPlanning/labs-zap-search/blob/develop/mirage/factories/project.js

**Comment by allthesignals** [comment]
Hi @trbmcginnis - next time you're here, let's get you set up on filling in the mockup API factory with appropriate faker.js methods: https://github.com/NYCPlanning/labs-zap-search/blob/develop/mirage/factories/project.js.

**Comment by allthesignals** [comment]
I will give you a brief tutorial

**Comment by chriswhong** [comment]
Stale
