### ISSUE TITLE
Handle empty project attributes (BBL, keywords, addresses, etc)

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zap-search#307]
Projects with no known BBLs show: "BBLS:", show blank map

**Comment by trbmcginnis** [comment]
![image](https://user-images.githubusercontent.com/26672885/44272231-3d806f00-a20a-11e8-9673-2a7b1e45fc51.png)

![image](https://user-images.githubusercontent.com/26672885/44272251-512bd580-a20a-11e8-9929-4bae83ad9744.png)

Hebrew home for the aged says "not mapped" on the filter view but has bbls on the project view
