### ISSUE TITLE
Find Projects button should be grayed if on that page

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zap-search#316]
![Screen Shot 2018-07-12 at 4.57.18 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246455f16b7191a37cf1172c4f5e575ecc3c4a4356bcbbd671f3e57862804e0ebfd0385826c06f15aeb1d44ab701ba21d81e8db4ef8b44d2f42f67b6d5db1063474f4dcbed5727a19141c95df54ae54f5ca4153367e1772431.png)

**Comment by hannahkates** [comment]
This goes in Labs-UI
