### ISSUE TITLE
"0 projects" view should show friendly Google-style message

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zap-search#322]
![Screen Shot 2018-07-12 at 5.12.06 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246455f16b7191a37df113294f5f595ecc3c4a4356bcbbd671f3e57862804e0ebfd0385826c06f15aeb1d44ab701ba21d81e8db4ef8b44d2f42f67b6d5db1063474f4dcbed5727a19e41c95df54ae54f5cad1a356ae3722431.png)

Similar to:
![Screen Shot 2018-07-12 at 5.13.27 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246455f16b7191a37df113284f5d585ecc3c4a4356bcbbd671f3e57862804e0ebfd0385826c06f15aeb1d44ab701ba21d81e8db4ef8b44d2f42f67b6d5db1063474f4dcbed5727a19e41c95df54ae54e55a4113466e67f2431.png)

**Comment by chriswhong** [comment]
From #322, add a reset filters button to this friendly view
