### ISSUE TITLE
If project name search does not return anything, suggest using address

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zap-search#348]

**Comment by hannahkates** [comment]
Add "search for address" (searching for address string in data) functionality to the free-form project description search

**Comment by andycochran** [comment]
This might be confusing. In many cases, the project name is an address. The search filter lets you find a string in certain project fields (name, brief, applicant). Adding the text "search for address" might confuse users, making them expect geocoded results. Explicit address search should happen in the map.
