### ISSUE TITLE
Link to community district profiles in project view

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zap-search#349]
![Screen Shot 2018-07-13 at 1.25.55 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246455f06b7191a379f1102e4f5a5a5ecc3c4a4356bcbbd671f3e57862804e0ebfd0385826c06f15aeb1d44ab701ba21d81e8db4ef8b44d2f42f67b6d5db1063474f4dcbed5727a19041c95df54ae44d57a314336be3702431.png)

**Comment by trbmcginnis** [comment]
Done! Fixed by PR #383
