### ISSUE TITLE
ZAP front page - slider issue

### ISSUE THREAD

**Issue by JosephBM** [NYCPlanning/labs-zap-search#360]
Hi all. I found a ZAP issue on the front page. For the sliders, I can't get the front slider to land on the year of 1980. The second slide works fine, but I can't set it as a start date. It jumps to 1979 or 1981. I tried on Rachaele's PC and she had the same issue. Thanks!

**Comment by rraynoff** [comment]
I'm now having the same problem starting the date slider at 2014. It jumps to 2013 or 2015.

**Comment by chriswhong** [comment]
[https://i.stack.imgur.com/z94gY.png]

**Comment by hannahkates** [comment]
Also the slider unpredictably slips around intervals, hard to control granularly. May be related to rounding

**Comment by andycochran** [comment]
I tried to work on this. But it's… complicated. We're using `ember-cli-nouislider`'s `step`option. But it doesn't seem to be working the same was that it does in the [docs](http://kennethkalmer.github.io/ember-cli-nouislider/#/options). We're setting `step=1`, which seems weird. Shouldn't it be set to the number of years between now and 1970? Also, when logging the dates from the slider, the left one is sometimes 0 and sometimes >0 when set to 1970. There's something fishy happening.

**Comment by allthesignals** [comment]
> I tried to work on this. But it's… complicated. We're using `ember-cli-nouislider`'s `step`option. But it doesn't seem to be working the same was that it does in the [docs](http://kennethkalmer.github.io/ember-cli-nouislider/#/options). We're setting `step=1`, which seems weird. Shouldn't it be set to the number of years between now and 1970? Also, when logging the dates from the slider, the left one is sometimes 0 and sometimes >0 when set to 1970. There's something fishy happening.

@andycochran do you have a branch for this?
