### ISSUE TITLE
Milestone - RS Cert/Ref name might be misleading

### ISSUE THREAD

**Issue by ajamespowell** [NYCPlanning/labs-zap-search#361]
The "Application Certified / Referred at City Planning Commission Review Session" milestone implies that all projects that went to RS were certified or referred when there are other outcomes that could have happened at the meeting. Maybe change the milestone name to "Application Reviewed at City Planning Commission Review Session"?
![image](https://user-images.githubusercontent.com/30417624/42779297-fd8f42c8-890d-11e8-8d48-142ea25cba6a.png)

**Comment by trbmcginnis** [comment]
![image](https://user-images.githubusercontent.com/26672885/43270775-e0de90b2-90c3-11e8-84d1-7e9ae7e1ae20.png)

**Comment by trbmcginnis** [comment]
I altered the name, I'm confused as to what the difference is between "Application Reviewed at City Planning Commission Session" and "City Planning Commission Review"?

**Comment by SomeCityBureaucrat** [comment]
Alex, this is the milestone for referring or certifying projects - what other actions could happen?  I think we should change it back.

**Comment by ajamespowell** [comment]
Ryan, The milestone is for both referring and certifying projects. But the projects can have other outcomes at the meeting (milestone) so that's why I encouraged the change. The other outcomes include: Held, Laid Over, Return to Review Session.
