### ISSUE TITLE
Project (Inwood Neighborhood Rezoning) displaying as "Completed", still in ULURP

### ISSUE THREAD

**Issue by ajamespowell** [NYCPlanning/labs-zap-search#364]
On the project search page (with multiple projects) this project shows as "Completed" but on it's [project page](https://zap.planning.nyc.gov/projects/P2016M0065) it's status is "In Public Review".

**Comment by chriswhong** [comment]
Which one is correct?

**Comment by ajamespowell** [comment]
The project page.

**Comment by chriswhong** [comment]
This was an issue with the materialized view that we use for search not staying up to date.  Re-opened #115 to address the issue, closing this.
