### ISSUE TITLE
Unable to open East Harlem Neighborhood Rezoning

### ISSUE THREAD

**Issue by ajamespowell** [NYCPlanning/labs-zap-search#366]
I'm able to find the record through the search but when I click the record I get a "Page Not Found"
![image](https://user-images.githubusercontent.com/30417624/42844854-40d8dd6c-89e2-11e8-9007-d0f66c69b146.png)

![image](https://user-images.githubusercontent.com/30417624/42844869-4edf47a2-89e2-11e8-8f8d-4a5c9fba6265.png)

**Comment by hannahkates** [comment]
Both of these issues are now resolved. Closing.
