### ISSUE TITLE
Some Boroughs mis-labeled in BBL tooltips

### ISSUE THREAD

**Issue by grantpezeshki** [NYCPlanning/labs-zap-search#379]
#89 related minor issue
Queens, Bronx, and Brooklyn BBLs are incorrectly labeled, for example this Queens BBL is labeled Bronx:
![image](https://user-images.githubusercontent.com/15787416/43278313-bd16a164-90d8-11e8-878b-0b2e23131d86.png)
... seems like the mapping is off; I think borocode should be: 
1=Manhattan
2=Bronx
3=Brooklyn
4=Queens
5=SI
... instead these labels are showing: 
1=Manhattan
2=Brooklyn
3=Queens
4=Bronx
5=SI

**Comment by chriswhong** [comment]
We have an incorrect borough mapping here: https://github.com/NYCPlanning/labs-zap-search/blob/aa92e3ec6d4fa961f7956eee8871036e5c2f9645/app/components/project-bbl.js#L13-L18

Thanks for pointing this out @grantpezeshki !

**Comment by chriswhong** [comment]
Hotfixed in febdd2321684d4f9782a2c0f9454f9d22784e6d5, closing

**Comment by chriswhong** [comment]
First fix had the wrong variable types, this one actually gets it working: f1243e37a3dbf55a86db2a31cd01fa1b5adf9cb8
