### ISSUE TITLE
Project not showing correct status

### ISSUE THREAD

**Issue by ajamespowell** [NYCPlanning/labs-zap-search#382]
Lead planner for 509 W. 34th Street (HY cert applications) requested that the application status on the portal is made withdrawn. When I went to deactivate it for the planner I noticed that the public status was already withdrawn. I deactivated the project yesterday and the status for the project still hasn't changed. 
https://zap.planning.nyc.gov/projects/P2015M0129

**Comment by SomeCityBureaucrat** [comment]
I deactivated each action for the project giving the reason for deactivation as "Withdrawn" is this the issue you're trying to address?

**Comment by ajamespowell** [comment]
Kind of. Looking back at my issue I think the original concern was the project status (highlighted in screenshot) but this doesn't show "withdrawn" right? If it doesn't then yes you've fixed this issue and we should close it. 

![image](https://user-images.githubusercontent.com/30417624/43481522-2aa136fa-94d4-11e8-8792-9c1c134f91f9.png)
