### ISSUE TITLE
BK CD 7 Projects Not Appearing in ZAP Search

### ISSUE THREAD

**Issue by ajamespowell** [NYCPlanning/labs-zap-search#393]
(submitting this on behalf of a planner. Tried figuring it out on my own but I don't know how the portal grabs zap data for mapping both for the CD and on the project search map)

When filtering on the public ZAP Search for Brooklyn Community District 7, project stage 'Filed' or 'In Public Review,' at least two projects are missing:

57 Caton Place (In Public Review)
Industry City Land Use Actions (Filed)

Both appear to have the correct addresses and CD designation in their ZAP records.

**Comment by hannahkates** [comment]
Now resolved, seems likely to have been a data issue
