### ISSUE TITLE
QA/QC document file names

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#413]
**Objectives:**
1. Identify which files don't match the predictable naming convention **Things to look for:**
    - What are outliers?
    - How many? LOE to clean up
2. Specifically for DOB/HPD letters, rename the files to the new naming convention in the process.

**File naming convention:**
- **Letters to DOB/HPD**
  - Old naming scheme: DOB[6-7 alphanumeric ULURPNO][3 alphabetical char ACTION]. Ex: DOB070194ZCM.pdf
    - Note: ULURP number vary between 6-7 digits. If the total file name is 13 character instead of 12, that means the ULURP number is 7 characters. We don't need to capture the actions.
  - New naming scheme: [ULURPNUM]_[AGENCY]. Ex: 070194_DOB.pdf or 070194A_HPD.pdf
- **Comments from Community Boards, Borough President, and Borough Boards**
  - Community Board: [ULURPNO]_[Boro][2 number digits]. Ex: 070194_Q04.pdf
  - Borough President: [ULURPNO]_[Boro]BP Ex: 070194_QBP.pdf
  - Borough Board: [ULURPNO]_[Boro]BB Ex: 070194_QBB.pdf

**Comment by hannahkates** [comment]
- What are outliers?
- How many?
- LOE to clean up
- Ability to lookup unique file w/ predictable patterns

**Comment by allthesignals** [comment]
Include log to track what was changed

**Comment by allthesignals** [comment]
"**Letters to DOB/HPD**" Files with inconsistent naming:

 - [ ] D0B190146ZCM.pdf
 - [ ] DOB 170348 ZCK.pdf
 - [ ] DOB000617(A)ZAX.pdf
 - [ ] DOB020333ZCQ - Copy.pdf
 - [ ] DOB020381AZSQ - Copy.pdf
 - [ ] DOB020499AZSM - Copy.pdf
 - [ ] DOB020594a.pdf
 - [ ] DOB050237SK .pdf
 - [ ] DOB050237ZSK .pdf
 - [ ] DOB060289ZSX.substantialCompliance.pdf
 - [ ] DOB060492(A)ZSM.pdf
 - [ ] DOB060493(A)ZSM.pdf
 - [ ] DOB090443ZSK.subCompliance.pdf
 - [ ] DOB090468ZCM.SubstantialCompliance.pdf
 - [ ] DOB110060BZSK.PDF
 - [ ] DOB110108 ZCK.pdf
 - [ ] DOB110109 ZCK.pdf
 - [ ] DOB110119ZSM.SubstantialCompliance.pdf
 - [ ] DOB110273ZCM.PDF
 - [ ] DOB110274ZCM.PDF
 - [ ] DOB120141.pdf
 - [ ] DOB130144RCR (2).pdf
 - [ ] DOB130395ZCM.substantialCompliance.pdf
 - [ ] DOB140159.pdf
 - [ ] DOB150008ZAR (2).pdf
 - [ ] DOB150186 ZCM.pdf
 - [ ] DOB150276cmm.pdf
 - [ ] DOB150288ZMX - Copy.pdf
 - [ ] DOB150327 ZSK.pdf
 - [ ] DOB150372 ZCK.pdf
 - [ ] DOB160010RCR (2).pdf
 - [ ] DOB160063ZCM_DOB.pdf
 - [ ] DOB160083RCR rev. 1.14.2016.pdf
 - [ ] DOB160107CMM_160108CMM_160109CMM.pdf
 - [ ] DOB160157ZCK.PDF
 - [ ] DOB160167ZCM_160168ZCM.pdf
 - [ ] DOB160191RCR .pdf
 - [ ] DOB160202RCR .pdf
 - [ ] DOB160280ZCQ_EXECUTED.pdf
 - [ ] DOB160281CMQ_EXECUTED.pdf
 - [ ] DOB160329RCR corrected.pdf
 - [ ] DOB160330RCR corrected.pdf
 - [ ] DOB160338ZSM_160339ZSM.pdf
 - [ ] DOB160397RCR corrected letter.pdf
 - [ ] DOB160399RCR .pdf
 - [ ] DOB160400RCR .pdf
 - [ ] DOB16099ZAR.pdf
 - [ ] DOB170023RCR .pdf
 - [ ] DOB170137 ZSM.pdf
 - [ ] DOB170144ZCR .pdf
 - [ ] DOB170235ZSM.PDF
 - [ ] DOB170236ZSM.PDF
 - [ ] DOB170237ZSM.PDF
 - [ ] DOB170288RCR .pdf
 - [ ] DOB170289RCR .pdf
 - [ ] DOB170307RCR.PDF
 - [ ] DOB170325RCR.PDF
 - [ ] DOB170341RCR.PDF
 - [ ] DOB170402RCR corrected letter.pdf
 - [ ] DOB170403RCR corrected letter - Copy.pdf
 - [ ] DOB170452 ZSM.pdf
 - [ ] DOB170462RCR .pdf
 - [ ] DOB170464 ZSM.pdf
 - [ ] DOB170465 CMM.pdf
 - [ ] DOB1800118RCR .pdf
 - [ ] DOB1800119RCR .pdf
 - [ ] DOB180048 ZCX.pdf
 - [ ] DOB180072ZCM_EXECUTED.pdf
 - [ ] DOB180103RCR .pdf
 - [ ] DOB180104RCR .pdf
 - [ ] DOB180104RCR_.pdf
 - [ ] DOB180105RCR .pdf
 - [ ] DOB180105RCR_.pdf
 - [ ] DOB180119RCR .pdf
 - [ ] DOB180159 ZCK.pdf
 - [ ] DOB770657AZMX (2).pdf
 - [ ] DOB800623(I)ZSM.pdf
 - [ ] DOB830094(B)ZMK.pdf
 - [ ] DOB851031D ZSQ.pdf
 - [ ] DOB910478EZMK.PDF
 - [ ] DOB920493(J)ZAM.pdf
 - [ ] DOB960008 ZCM.pdf
 - [ ] DOBLTRC170192ZSM_C170193ZSM.pdf
 - [ ] DOBM820479BZMQ.pdf
 - [ ] DOBM850004azcm.pdf
 - [ ] DOB_170292_CMK & 170293_CMK.pdf
 - [ ] DOB_180035ZCM.pdf
