### ISSUE TITLE
Users want to be able to identify when projects are overlapping on the same site

### ISSUE THREAD

**Issue by trbmcginnis** [NYCPlanning/labs-zap-search#429]
## Problem
- 46% of all projects share a centroid with another project
- The maximum number of projects sharing a single centroid is 34
- Projects with the same centroid appear as one mapped point; users don’t know if there are multiple projects at a single point 
- In a set of projects sharing a centroid, only the top point is clickable; users can’t click on other projects in that set

_Related problems:_ 
- Users need to see all projects at a specific location or within a specified radius 
- Projects visualized as centroids are more and more misleading as the map is zoomed in, especially once tax lot and building footprints become visible 

## Solution
- [x] Clicking a project centroid on the map no longer navigates directly to that project
- [x] To navigate to a project view, users must select that project from the list 
- When a point is clicked
  - [x] A “filter point” is added to the map
  - [x] Map is zoomed to that point (fitBounds all intersecting projects)
  - [x] A new “Distance from point” filter is enabled 
- When a GeoSearch result is selected
  - [x] A “filter point” is added to the map
  - [x] Map is zoomed to that point (fitBounds all intersecting projects)
  - [x] A new “Distance from point” filter is enabled 
- [x] The “Distance from point” filter restricts the project list results to a specified radius from the user-defined filter point (based on intersecting BBLs, not centroids)
  - [x] Controls allows user to adjust length of radius (slider, text input)
  - [x] Radius defaults to 600 ft
- [x] Subsequent clicks move the filter point 
- [x] Subsequent geosearch searches move the filter point 
- [x] While the “Distance from point” filter is enabled, any map click (not just point clicks) sets/moves the filter point location — this allows the user to see projects within a radius of a specific location that is not a project centroid 
- [x] If “Distance from point” filter is enabled but no filter point is set, filter should show “Click the map to add a point” instead of controls 
- [x] Clearing the search removes the filter point
- [x] Disabling the “Distance from point” filter removes the filter point
- [x] When map is zoomed to a level at which tax lot and building footprints become visible, projects should be visualized as transparent polygons instead of points (styled similar to streets.planning.nyc.gov) which are highlighted when their corresponding list item is hovered

Enabled “Distance from point” filter (with and w/o a filter point): 

![image](https://user-images.githubusercontent.com/409279/55109889-32999100-50ad-11e9-8b02-319de1dea509.png)

![image](https://user-images.githubusercontent.com/409279/55109906-3b8a6280-50ad-11e9-9bfd-0f4b49d5ca12.png)

Filter point set to zero radius: 

![image](https://user-images.githubusercontent.com/409279/55109933-48a75180-50ad-11e9-846a-fc207d527fcc.png)

Filter point set to larger radius: 
![image](https://user-images.githubusercontent.com/409279/55109955-55c44080-50ad-11e9-96fc-2e8ca556cb69.png)

![image](https://user-images.githubusercontent.com/409279/55109982-67a5e380-50ad-11e9-89cd-f74a96d0e885.png)

**Comment by andycochran** [comment]
Updated description based on this doc: https://docs.google.com/document/d/1Pz7npzvYgQ7VSzth0eW_d8bWeCU09fdRX5wBWrb88Kg/edit?usp=sharing
