### ISSUE TITLE
Include radius search feature

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#436]
User story: applicants are expected to research and report on recent land use activity surrounding their proposed project in their application. Building a tool that allows them to easily search for current and completed projects within a certain radius would allow them to more easily gather that information to streamline their application preparations.

**Comment by hannahkates** [comment]
The radius search should ideally use the polygons, instead of the centroid points, to capture more reliable results.

**Comment by andycochran** [comment]
Related to #429
