### ISSUE TITLE
Users want to be able to search by ULURP # only

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#448]
Right now, all the filters are additive, including ULURP number. So if a user searches for a ULURP number using the default filter settings, they won't be able to access that project if it's "complete." We should set up mutually exclusive searches for an ID vs. other filtering constraints that will return more than one project.

**Comment by hannahkates** [comment]
This filter will be combined with the project description filter. The existing filter should be removed once the functionality has been migrated into the combined search filter.

**Comment by andycochran** [comment]
This, as described, is solved by https://github.com/NYCPlanning/labs-zap-search/commit/d9ce7c17696810ceaa6c27627c444d457a4c0f54 (having no filters enabled by default).

**Comment by allthesignals** [comment]
Should this be closed? @andycochran - why is it "solved" but still open?
