### ISSUE TITLE
Distance filter slider should not go to zero

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-zap-search#464]
Currently, the map will `fitBounds()` the distance filter's dotted circle. But when the radius is zero, it zooms to the city level. I think there's no need for the slider to go to zero (especially given that we made it default to a larger radius for the cases where a centerpoint does not fall within a polygon). The lower limit of the slider could be something like 100ft — and just like the upper limit, it could be overridden with the input. 

Thoughts on what the lower limit should be? 

/cc @hannahkates @allthesignals

**Comment by hannahkates** [comment]
20 ft
