### ISSUE TITLE
Optimize spatial intersection for radius filter

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#474]
The radius query uses [`ST_Distance_Sphere`](https://postgis.net/docs/manual-1.4/ST_Distance_Sphere.html) to get project within the user-defined radius. 

```
const radiusQuery = distance_from_point[0] ? pgp.as.format('AND ST_Distance_Sphere(c.polygons, ST_MakePoint($1,$2)) <= $3', [...distance_from_point, ((radius_from_point / 5280) * 1609.34)]) : '';
```

[`ST_DWithin`](https://postgis.net/docs/ST_DWithin.html) might be much faster. Let's try refactoring the radius query to use it instead.

**Comment by trbmcginnis** [comment]
`ST_DWithin` along with indexes on both the `centroid` and `polygons` geometry columns in table `project_geoms` made the filter faster BUT it's the speed is still not ideal. 

Indexes were created with:

`CREATE INDEX centroid_index ON project_geoms USING gist(centroid);`
`CREATE INDEX polygons_index ON project_geoms USING gist(polygons);`

Also found another issue with zooming to the point, the old filtered projects will persist after a new point is created AND sometimes the map will zoom to an old location before zooming to the new one. 

Here's a photo of the old projects persisting before the map zooms in on the new one. This may also be slowing things down:

<img width="826" alt="persisting_radius_filter" src="https://user-images.githubusercontent.com/26672885/56045652-9fe52d00-5d0f-11e9-8ed9-7dfe9a0eb883.png">
