### ISSUE TITLE
Make filter tests less brittle

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#478]
- [ ] acceptance/filter-checkbox-test.js needs better IDs for each of the filter toggles for testing purposes https://github.com/NYCPlanning/labs-zap-search/blob/develop/tests/acceptance/filter-checkbox-test.js#L78

**Comment by allthesignals** [comment]
We should add ember-test-selectors: https://github.com/simplabs/ember-test-selectors

Adding this comment from source for more clarity on what the "brittleness" here is:

>   // Commenting these out until we implement a better named IDs for testing for each of the filters

**Comment by allthesignals** [comment]
Things being "hard to test" is usually a signal that there's a design flaw in the code itself. Adding more sophisticated test selectors would definitely help get around that, but maybe it's time to think about the filters becoming data-driven?

**Comment by allthesignals** [comment]
Started a branch in 478-fix-tests

**Comment by trbmcginnis** [comment]
Will do!
