### ISSUE TITLE
map.flyTo() should not request tiles until landed

### ISSUE THREAD

**Issue by trbmcginnis** [NYCPlanning/labs-zap-search#487]
Right now, tiles are being requested while `map.flyTo()` is in transit, meaning there are excessive requests to the backend. We should make it so that these requests do not happen until `map.flyTo()` is finished. This will help the radius filter run faster.

**Comment by trbmcginnis** [comment]
- Cancel requests don't come in fast enough for us to stop execution before the query is sent to the server. 
- There's no way to configure `map.flyTo()` to delay tile requests
- The query takes the same amount of time with or without the `radiusDistanceQuery`, so that's not what's causing the slow down
- Generating tiles from queries is slow and we can't currently cancel requests, so we're running a lot of unnecessary queries which is adding time to how long it takes to get the tiles that the frontend actually wants
- There should be a way in the frontend to cancel map actions. Right now, when radius filter is on, and a point is selected before a previously selected point has been zoomed to, the map will still zoom in to the prior point before zooming in to the most recent. This should be cancellable

**Comment by allthesignals** [comment]
@trbmcginnis what are the relevant mapbox-gl-js Github issues threads for this? Would love to document all that research into this.

I vaguely remember some discussion about MapboxGL's animation primitives needing to support this...
