### ISSUE TITLE
refine the query for actions that appear on project page

### ISSUE THREAD

**Issue by trbmcginnis** [NYCPlanning/labs-zap-search#49]
1. Has to have a **ULURP number** (even non-ULURP actions have ULURP numbers)
2. Any that have been deactivated or are a "mistake" should not appear--all actions should have an **approved project action status** (withdrawn should remain visible)

**Comment by andycochran** [comment]
@chriswhong Is this done?

**Comment by chriswhong** [comment]
No, not done yet.  

https://github.com/NYCPlanning/labs-zap-api/blob/develop/queries/projects/show.sql#L36-L50

Right now, it's only filtering out statuscode = "Mistake"

**Comment by chriswhong** [comment]
No longer relevant
