### ISSUE TITLE
Better message when results list is empty

### ISSUE THREAD

**Issue by trbmcginnis** [NYCPlanning/labs-zap-search#499]
When results list is empty, show a more detailed/more conspicuous message saying WHY it’s empty. We should show **which filters** are on in the message and why it may be limiting their search.

**Comment by allthesignals** [comment]
@andycochran any thoughts on this? Seems like it should... be a sentence somewhere? Perhaps:

## Hmm, no results. These filters are applied, perhaps change them:
 - Project Status
 - Radius Filter

**Comment by andycochran** [comment]
![image](https://user-images.githubusercontent.com/409279/56603393-b02dbf80-65cd-11e9-80f8-de908d49690e.png)

**Comment by allthesignals** [comment]
Project filters need people-friendly aliases, which is currently managed in the templates... 

This is another signal that perhaps filtering UI needs to be more data driven 🤷‍♂️
