### ISSUE TITLE
get zoning resolution section number and city council resolution number in data

### ISSUE THREAD

**Issue by trbmcginnis** [NYCPlanning/labs-zap-search#50]
Find this data

if it's a ULURP action that's been approved, it will have these numbers

**Comment by chriswhong** [comment]
Zoning Resolution and Council Resolution were added to the API in 311b69587af035270fbd109b3ffdae1447db8139.

Will work on getting these into the app now.

**Comment by chriswhong** [comment]
Got zr sections in, and links working in #69, still need to build links for Council Resolutions
