### ISSUE TITLE
Radius filter is unacceptably slow

### ISSUE THREAD

**Issue by trbmcginnis** [NYCPlanning/labs-zap-search#501]

**Comment by trbmcginnis** [comment]
New tiles are generated every time the map pans or zooms, meaning the tile query is being run every time the user moves around the map. Because we need to build geometries when we run radiusDistanceQuery, this query will run every time with the tiles query, which is why we were seeing radiusDistanceQuery repeated so many times in the backend. Right now, tiles are being requested while map.flyTo() is in transit, meaning there are excessive requests to the backend.

What we found out:

- Cancel requests don't come in fast enough for us to stop execution before the query is sent to the server.
- There's no way to configure map.flyTo() to delay tile requests
- The query takes the same amount of time with or without the radiusDistanceQuery, so that's not what's causing the slow down
- Generating tiles from queries is slow and we can't currently cancel requests, so we're running a lot of unnecessary queries which is adding time to how long it takes to get the tiles that the frontend actually wants
- There should be a way in the frontend to cancel map actions. Right now, when radius filter is on, and a point is selected before a previously selected point has been zoomed to, the map will still zoom in to the prior point before zooming in to the most recent. This should be cancellable

**Comment by trbmcginnis** [comment]
Things to explore:

- should we generate tiles separately for the geometries within the radius filter? That way we could generate these tiles ONLY when the map has finished flying to. How do we make it so that these tiles do not re-generate everytime the user zooms in/out or pans.

**Comment by chriswhong** [comment]
Idea:  Just use `jumpTo()` instead of `flyTo()` and there won't be a ton of intermediate tile requests.  I'm not clear on why we need to change the map view at all when the user toggles on the radius filter.  We should just leave it where it is IMHO and let them control it manually.

**Comment by chriswhong** [comment]
So, the other reason why the vector tiles take so long to come back from the DB is that we are running `ST_Transform()` on the geoms to convert them to webmercator.  I think we are actually doing it twice because it happens in the where clause too.

Carto's magic is automatically creating a webmercator geom column so you don't need to do this transform on the fly.  We should try this but need a way to keep it up to date

**Comment by chriswhong** [comment]
Another option is to just convert the geometry columns to webmercator so we don't have to transform them at all when making vector tiles. We don't really need to have them in WGS84.  It would mean more work to transform them when downloading data, and when adding new geometries.

**Comment by chriswhong** [comment]
I added webmercator columns to the staging DB and indexed them, and tested out the api without ST_Transform(), but not seeing a big performance increase :/

**Comment by trbmcginnis** [comment]
UPDATE:

From @chwong: The units are important, you can't get an actual "radius" unless you convert to geography. If you don't, the units are "degrees" which mean something very different east-west vs north-south.

So we're going to go with option 2 ^^ and create indexes for the geographies.

So I meant to bring up, we may be doing it wrong because we have to apply ALL the filters again when we generate a tile, so it's a complex query.
with possibly TWO spatial queries because we are doing radius AND clipping for the tile bounds
With a bit of refactoring, we could just store the project IDs associated with the filtering query.
Then when we query for a tile we just say WHERE projectid IN [..arrayofprojectIDS] AND (geom && tilebounds). Tile creation should be MUCH MUCH faster if we don't need to apply all this complex WHERE logic on each one

We already did this to generate the JSON we send back to the frontend for the listing. So we run run the ST_DWithin to generate a list of project IDs first, and then just run the tile query with this id list in the WHERE clause instead of radiusDistanceQuery. Right now we store the full query we used to generate the projects list, and we use the same query as a subquery to generate tiles. We could just store an array of projectids and make the tile queries MUCH faster.

We would store in the same place we are storing the query (memory cache):

https://github.com/NYCPlanning/labs-zap-api/blob/91aa952c819df5d1e2d55b7cd3c08eadf550dc24/routes/projects/index.js#L79

Every time the user changes filters, the whole process starts over.
Each time there is a new set of filters, we are running a complex query to get the projects list, and then running it again for EACH tile request. We can refactor and only do the complex query once, simplifying ALL tile requests. So as a user moves around the map without changing their query they will see improvements.
