### ISSUE TITLE
Get migrations up-to-date

### ISSUE THREAD

**Issue by trbmcginnis** [NYCPlanning/labs-zap-search#508]
- Add

**Comment by trbmcginnis** [comment]
- migration for adding indices to geometry columns in table `project_geoms` 
- creating transformed geometry columns with indices (project to

**Comment by trbmcginnis** [comment]
Been reading up on indexing on **geometry** (data lives on Cartesian plane like a map projection) vs. **geography** (data is made up of points on earth's surface, lat & long). Geography is more accurate but tends to take longer (up to 4x with over ~750 rows when tested in this [Medium blog post](https://medium.com/coord/postgis-performance-showdown-geometry-vs-geography-ec99967da4f0)).

**Comment by julialucyhogan** [comment]
my whole response to that is i love it sick researching, very interested to know what the results of your investigations are.

I wonder if someone with more mapping intel than me (you or matt or chris or whoever) can weigh in on what the actual benefits of converting to geogs are in this specific context. Are we doing it b/c it's a necessary increase in accuracy, or b/c we were just like oh it's more accurate let's be the most good as possible! ?

Also, you can check to see if a query uses a given index with EXPLAIN: https://www.postgresql.org/docs/9.6/using-explain.html might be helpful for turning some open questions/assumptions into cold hard FACTS.

**Comment by trbmcginnis** [comment]
UPDATE:

From @chwong: The units are important, you can't get an actual "radius" unless you convert to geography. If you don't, the units are "degrees" which mean something very different east-west vs north-south.

So we're going to go with option 2 ^^ and create indexes for the geographies.
