### ISSUE TITLE
Tags for ULURP and CEQR #s are missing in project list

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#512]
Each project should list its ULURP and CEQR numbers, as shown in screenshot below. These are missing on production.

![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/9e680401-18b5-4b25-af91-3def0d23cbf2)

**Comment by trbmcginnis** [comment]
Fixed by changing `^(\w+)` in create-materialized-view migration to `^(\\w+)` in PR 121

https://github.com/NYCPlanning/labs-zap-api/pull/121
