### ISSUE TITLE
Use milestone unique IDs to select milestones instead of dcp_name

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#518]
Replace the list of dcp_names here https://github.com/NYCPlanning/labs-zap-api/blob/develop/queries/projects/show.sql#L260

With the list of IDs here https://github.com/NYCPlanning/labs-zap-api/blob/develop/queries/projects/show.sql#L165

**Comment by trbmcginnis** [comment]
**Prepare CEQR Fee Payment**:   763beec4-dad0-e711-8116-1458d04e2fb8
**Prepare and Review FEIS**:     883beec4-dad0-e711-8116-1458d04e2fb8
**Prepare Filed Land Use Application**:     663beec4-dad0-e711-8116-1458d04e2fb8
**Prepare Filed Land Use Fee Payment**:     6a3beec4-dad0-e711-8116-1458d04e2fb8
**DEIS Notice of Completion Issued**:     843beec4-dad0-e711-8116-1458d04e2fb8
