### ISSUE TITLE
Send rec form content to ZAP CRM

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#547]
See `dcp_communityboarddisposition` tab in [ZAP CRM metadata](https://drive.google.com/file/d/1jLx4YL2gyhBE20zG9mTLFiTTxdQb0YHL/view?usp=sharing)

SEND
- [ ] dcp_representing
- [ ] dcp_nameofpersoncompletingthisform
- [ ] dcp_title
- [ ] dcp_dateofvote
- [ ] dcp_votelocation
- [ ] dcp_totalmembersappointedtotheboard _(not shown for BP unless dcp_representing is Borough Board)_
- [ ] dcp_wasaquorumpresent _(not shown for BP unless dcp_representing is Borough Board)_
- [ ] dcp_boroughboardrecommendation _(filled in if dcp_representing is Borough Board)_
- [ ] dcp_communityboardrecommendation _(filled in if dcp_representing is Community Board)_
- [ ] dcp_boroughpresidentrecommendation _(filled in if dcp_representing is Borough President)_
- [ ] dcp_votingagainstrecommendation _(not shown for BP unless dcp_representing is Borough Board)_
- [ ] dcp_votinginfavorrecommendation _(not shown for BP unless dcp_representing is Borough Board)_
- [ ] dcp_votingabstainingonrecommendation _(not shown for BP unless dcp_representing is Borough Board)_
- [ ] dcp_consideration
- [ ] dcp_datereceived (calculate upon submission)

**Comment by godfreyyeung** [comment]
Putting a rough draft of how Frontend Models will translate to CRM fields: 

?? = needs confirmation.

**General Info** (still unclear how much of this is pre-populated in CRM)

- Recommendation.recommendation  -- dcp_name
- Recommendation.Project -- dcp_project
- Recommendation.Project.(dcp_)projectname -- dcp_dispositionprojectname
- Recommendation.Actions -- dcp_projectaction
- Recommendation.Project. dcp_ulurpnumber
- Recommendation.Project.borough -- dcp_borough
- Recommendationd.Project.communitydistrict -- cp_communitydistricts
- Recommendation.Project.dcp_ceqrnumber -- dcp_ceqrnumber
- Recommendation.docketDescription --   dcp_docketdescription
- Recommendation.visibility --  dcp_visibility
- Recommendation.isActive  -- statecode
- Recommendation.status -- statuscode

**Public Hearing**

- Recommendation.dcp_ispublichearingrequired --  dcp_ispublichearingrequired
- Recommendation.action.project.hearing.date -- dcp_dateofpublichearing
- Recommendation.action.project.hearing.location -- dcp_publichearinglocation

**Disposition**

- Recommendation.User?? -- dcp_recommendationsubmittedby
- Recommendation.User.landUseParticipant -- dcp_representing
- Recommendation.User.name?? --  dcp_nameofpersoncompletingthisform
- Recommendation.title?? --  dcp_title
- Recommendation.dateVoted -- dcp_dateofvote
- Recommendation.voteLocation -- dcp_votelocation
- CommunityBoardRecommendation.totalBoardMembers --  dcp_totalmembersappointedtotheboard _(not shown for BP unless dcp_representing is Borough Board)_
- CommunityBoardRecommendation.didQuorumExist -- dcp_wasaquorumpresent _(not shown for BP unless dcp_representing is Borough Board)_
- BoroughBoardRecommendation.recommendation -- dcp_boroughboardrecommendation _(filled in if dcp_representing is Borough Board)_
- CommunityBoardRecommendation.recommendation --dcp_communityboardrecommendation _(filled in if dcp_representing is Community Board)_
- BoroughPresidentRecommendation.recommendation -- dcp_boroughpresidentrecommendation _(filled in if dcp_representing is Borough President)_
- CommunityBoardRecommendation.votesAgainst --  dcp_votingagainstrecommendation _(not shown for BP unless dcp_representing is Borough Board)_
- CommunityBoardRecommendation.votesInFavor -- dcp_votinginfavorrecommendation _(not shown for BP unless dcp_representing is Borough Board)_
- CommunityBoardRecommendation.votesAbstain -- dcp_votingabstainingonrecommendation _(not shown for BP unless dcp_representing is Borough Board)_
- Recommendation.consideration -- dcp_consideration
- Recommendation.dateReceived -- dcp_datereceived (calculate upon submission)
