### ISSUE TITLE
API must provide projects for LUP user (front-end/back-end parity)

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#550]
**[UPDATED 9/12]**

**Create new route that grabs projects for each user**
Based on all project IDs associated with a user in `dcp_projectlupteam`, query for all those project details for the project listing.

**SQL for getting the projects, flagging which tab they belong on, and grabbing necessary attributes:**
https://github.com/NYCPlanning/labs-zap-api/pull/192/files

**Remaining work:**
- [x] Create an API route that uses the SQL above
- [x] Make front-end and back-end attribute names match
- [ ] Double check with SMEs that all filtering conditions are correct

**Comment by hannahkates** [comment]
![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/c30a972c-3f4f-42ab-8491-cd360a592113)

**Comment by hannahkates** [comment]
![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/4d5e361b-c79c-49c2-9c70-3a195a8e2226)

**Comment by hannahkates** [comment]
LUP milestone IDs:

- Community Board Review 923beec4-dad0-e711-8116-1458d04e2fb8
- Borough President Review 943beec4-dad0-e711-8116-1458d04e2fb8
- Borough Board Review 963beec4-dad0-e711-8116-1458d04e2fb8

**Comment by julialucyhogan** [comment]
@hannahkates all three milestone ids you provided above are the same :) 

also, if the same user is going to be acting as BP and BB, do all the projects for BOTH actions show up for that user?
