### ISSUE TITLE
[new API] Milestone sequencing is wrong

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#575]
Milestone sequencing is wrong with the milestones showing up in a jumbled order on devlocal. 
Example to compare: https://zap.planning.nyc.gov/projects/P2016Q0306

**Comment by allthesignals** [comment]
@hannahkates just want to confirm that the sequencing in this project (https://zap.planning.nyc.gov/projects/P2016Q0306) is correct? It looks disordered, too. I want to make sure I'm comparing with the correct one.
