### ISSUE TITLE
Endless requests to mirage `/users?me=true` endpoint

### ISSUE THREAD

**Issue by godfreyyeung** [NYCPlanning/labs-zap-search#583]
At the tip of `develop-future`, something about the mirage config's `this.get('/users')` endpoint is causing endless GET requests to `/users?me=true`  

![Screen Shot 2019-08-20 at 4.29.52 PM.png](https://images.zenhubusercontent.com/5ced7833554ce77a5db49edf/23e9a313-4b97-4b5b-98d9-5c250be2cfed)

**Comment by hannahkates** [comment]
No longer relevant
