### ISSUE TITLE
Update dashboard milestone icons

### ISSUE THREAD

**Issue by godfreyyeung** [NYCPlanning/labs-zap-search#657]
Which icons should be used and how many?

For project cards on the dashboard's Upcoming and Reviewed tabs, what icons should be used for different milestone status' on the "Upcoming" and "Reviewed" pages?
- e.g. 'Not Started', 'In Progress', 'Overridden'?

**Comment by andycochran** [comment]
https://docs.google.com/drawings/d/1NNVpeI7wFMOFDx7bLgvM2dwNUPHP2mBQG7rzxg8jp3k/edit?usp=sharing

**Comment by allthesignals** [comment]
This is ready to implement

**Comment by allthesignals** [comment]
See the icons for milestones — @andycochran what are the asset names for these? Are they fontawesome icons?

**Comment by andycochran** [comment]
I've added an icons comment to [the tab wireframes](https://docs.google.com/drawings/d/1NNVpeI7wFMOFDx7bLgvM2dwNUPHP2mBQG7rzxg8jp3k/edit) with the Font Awesome icon name and prefixes. 

![image](https://user-images.githubusercontent.com/409279/65699806-a3b20500-e04c-11e9-8807-83e0b31d3e03.png)
