### ISSUE TITLE
Filter milestone listing per LUP tab

### ISSUE THREAD

**Issue by godfreyyeung** [NYCPlanning/labs-zap-search#658]
Which milestones should be shown?

For project cards under "Upcoming" and "To Reviewed" tabs, how do we handle/display the many milestones associated with a project? Do we only display the few milestones before and after the 'In Progress' milestone? (Currently in #656  , all milestones are listed)

Note: make sure to include City Council vote. This is important for CBs.

**Comment by andycochran** [comment]
https://docs.google.com/drawings/d/1NNVpeI7wFMOFDx7bLgvM2dwNUPHP2mBQG7rzxg8jp3k/edit?usp=sharing

**Comment by allthesignals** [comment]
This is ready to implement

**Comment by allthesignals** [comment]
Consider creating computed properties on the project model which will filter out the milestones

**Comment by hannahkates** [comment]
This has been implemented on the upcoming and review tabs, but not yet for archive and to review. @godfreyyeung are you planning to do a follow up PR for those?
