### ISSUE TITLE
show-project route only show rec and hearing buttons if project assigned to user

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#660]
- Buttons should only appear if 
  - user is logged in
  - user is assigned to project

See notes on implementation in the corresponding API PR: https://github.com/NYCPlanning/labs-zap-api/pull/201

**Comment by allthesignals** [comment]
The API implicitly associates projects to a user if and only if that user has been assigned to that project.

So, if the currently viewed project (the show-project route) associated with that user `user.projects.mapBy('id')`, then show the buttons

**Comment by allthesignals** [comment]
Original comment on #681:

@godfreyyeung I think I know what this means... the payload schema is difference when you load the project from my-projects. This is also an API issue. Essentially ,when you load the projects from the my-projects view, the API will use a different query and that response body will include a property that specifies the "tab status" of that project. If the project is loaded in the regular show-project view, it isn't.

We could either always force a reload when fetching user projects (don't know how to do that), or we could just unify the way the API requests project-related data, which is the better long-term approach.

**Comment by godfreyyeung** [comment]
I agree with unifying the api requests for project-related data!
