### ISSUE TITLE
Send hearing form data to ZAP CRM

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#668]
See `dcp_communityboarddisposition` tab in [ZAP CRM metadata](https://drive.google.com/file/d/1jLx4YL2gyhBE20zG9mTLFiTTxdQb0YHL/view?usp=sharing)

There are two different outcomes for submitting hearings:
1. If the LUP submits real hearing details, send
- [x] dcp_dateofpublichearing
- [x] dcp_publichearinglocation
2. If the LUP opts out of submitting hearing info, send
- [x] dcp_ispublichearingrequired

**Comment by allthesignals** [comment]
One thing to consider: for multiple dispositions, we need to make sure failed network requests are handled... consider doing in batch (post to /dispositions with an array of objects)

**Comment by hannahkates** [comment]
It looks like the "opt out" data isn't being successfully written to CRM, and/or the front-end isn't looking for the correct attribute to know that a user opted out. I opted out of a hearing for a project, waited for the ETL to run, and the front-end didn't reflect that I had opted out.

**Comment by hannahkates** [comment]
Front-end work required:
- [ ] Add dcp_ispublichearingrequired (isPublicHearingRequired) to the assignment model
- [ ] Make sure assignment.hearingsSubmittedOrWaived is using real data from dcp_ispublichearingrequired
- [ ] Write False to isPublicHearingRequired

Back-end work required:
- [ ] Add dcp_ispublichearingrequired to dcp_communityboarddisposition SQL queries
- [ ] Add dcp_ispublichearingrequired to disposition controller
- [ ] Add dcp_ispublichearingrequired to disposition entity
