### ISSUE TITLE
Update error handling for `onConfirm` for hearing form

### ISSUE THREAD

**Issue by trbmcginnis** [NYCPlanning/labs-zap-search#670]
Currently, the action `onConfirm` that saves the hearing information to the model uses a `try catch` block to handle errors. This needs to be updated and tested.

For more info visit PR 669 --> https://github.com/NYCPlanning/labs-zap-search/pull/669

**Comment by allthesignals** [comment]
- [ ] Simulate an error response in Mirage via the acceptance test
 - [ ] Make sure the try-catch block here is actually needed
