### ISSUE TITLE
Validate Recommendation submission form

### ISSUE THREAD

**Issue by godfreyyeung** [NYCPlanning/labs-zap-search#671]
- Require wasquorumpresent, recommendation, comment for all dispositions.
- Require vote for each disposition unless the user selects "Waived" as recommendation value.

**Comment by allthesignals** [comment]
@godfreyyeung let me know how complicated this gets. To some extent, we should be having the backend provided validation responses in the form of errors, meaning that if I submit something invalid, the API will respond with an errors array of objects detailing what was invalid, where. I think this is probably the ideal solution, but it could take time. Let me know your thoughts on this.

**Comment by godfreyyeung** [comment]
@allthesignals Yeah this could get complicated on the frontend. I think at this point  it means some manual, less-scalable code in the `onContinue` actions, instead of relying on changesets for everything.  Less ideal, but good for moving on quicker.
