### ISSUE TITLE
Additional conditional to show "submit hearing/rec" btn on proj profile  

### ISSUE THREAD

**Issue by godfreyyeung** [NYCPlanning/labs-zap-search#681]
Add the additional conditional of displaying the submit hearing/rec buttons only if the project has a "to-review" tab value. 
Display the project.teammemberrole in the button. "Submit <project.teammemberrole> Hearing/rec"

This depends on the new project payload  schema in Issue #

**Comment by allthesignals** [comment]
@godfreyyeung I think I know what this means... the payload schema is _difference_ when you load the project from `my-projects`. This is also an API issue. Essentially ,when you load the projects from the my-projects view, the API will use a different query and that response body will include a property that specifies the "tab status" of that project. If the project is loaded in the regular show-project view, it isn't.

We could either _always_ force a reload when fetching user projects (don't know how to do that), or we could just _unify the way the API requests project-related data_, which is the better long-term approach.

This is related to #660.

Opening a new issue for API work.

**Comment by allthesignals** [comment]
We actually don't want this — we wan the button to show up on exaclty exactly the following conditions:

- Buttons should only appear if 
  - user is logged in
  - user is assigned to project

**Comment by allthesignals** [comment]
Closing in favor of #660
