### ISSUE TITLE
Rec button appears after LUP submits hearing or opts out of hearing

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#707]
On the "To Review" tab, the user will only see one button at time. 
- First they will see a "schedule hearing" button. Under the button they will see an option to opt out of submitting a hearing. 
- The opt out option needs to include a warning that opting out of a CB rec on a ULURP project means they are also opting out of a submitting an official recommendation (although they will still be able to submit via the app)
- This opt out indication needs to be saved to CRM (probably in the hearing location field)
- After they have either submitted their hearing or opted out of submitting a hearing, the "schedule hearing" button will be replaced with a "submit recommendation" button.

Notes on implementation:
- ~Write "Waived" to public hearing location field on model~ Write "no" to `dcp_ispublichearingrequired` on the dispositions
- Modal component should provide warning that opting out of a CB hearing on a ULURP project means they are also opting out of a submitting an official recommendation (although they will still be able to submit via the app)
- Recommendation button should never appear on "upcoming" tab

![image](https://user-images.githubusercontent.com/409279/65702627-571cf880-e051-11e9-9b1e-07dc48cf843a.png)

**Comment by allthesignals** [comment]
There'll be a lot of conditional template logic for this. Let's be sure to keep this in a component. There should be computed properties on the component that reference the relevant model properties: 

`hasHearing: computed('model.someProp,model.someOtherProp')`

The project model should already have access to the dispositions (hearing), and we should be able to list those hearings conditionally. Consider a computed property on the model record to filter disposition records accordingly.

At the moment it's unclear how we can tell CRM that the user has opted out of a hearing. Suppose for now that it will just set some string value on the record.

Here's the sequence:
 - [ ] Write some acceptance tests for the view based on the design above. It should assert stuff based on the model behavior. See what downstream questions arise from this.
 - [ ] Get the mirage state in a place that it can simulate these scenarios. 
 - [ ] Get tests to pass.

**Comment by andycochran** [comment]
Draft language for the modal when opting out of hearings (to be confirmed w/ SME): 

> Without proper notice of a public hearing, the [Participant Type]'s recommendation does not comply with City Charter requirements. NYC Planning will still accept a recommendation, but a disapproval will not trigger an automatic City Council call up.
> 
> <a href="#">**Confirm Opt-Out**</a>
