### ISSUE TITLE
When "to-review" tab empty, the view is blank, confusing

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zap-search#710]
![image.png](https://images.zenhubusercontent.com/5ca23922d9fcf5278d715977/56d4c2bd-5269-4528-9f3a-0276dd00aadd)

We should add some kind of "all done" or "no projects to review!" — maybe even more "something not right? please contact us."

**Comment by andycochran** [comment]
I got this one. 😎
