### ISSUE TITLE
Colors for "Filed" vs. "In Public Review" are indistinguishable

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#743]
For people with color blindness, the "Filed" vs. "In Public Review" point colors are indistinguishable. We need to change the colors to be accessible. See screenshot below.

We should fix this before we make these two project status categories the default projects that are visible (see #679)

![Screen Shot 2019-10-03 at 2.11.47 PM.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/adea4530-f89f-4b5f-8f41-d005642cefd9)

**Comment by andycochran** [comment]
Per @kchanba's recommendations, let's go with: 
- `#59ca3b` Filed
- `#0a7dcb` In Public Review
- `#a6cee3` Complete
