### ISSUE TITLE
Change width of hearing opt out modal on LUP upcoming and to review tabs

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#751]
There's an orphan word on the last line. We should make the width narrower or a little wider so it doesn't look awkward

![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/316d794a-9060-463d-9e54-e119b549d8b3)

**Comment by andycochran** [comment]
This is irrelevant as the opt-out has switched to a modal.
