### ISSUE TITLE
LUP hearing opt out modal overlaps with map tools on project page

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#752]
On the LUP user's view of a project page, if they click the hearing opt out button, the modal weirdly overlaps with the map's tools. We should correct the layering so the map tools don't show up on top.

![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/a51f1a7b-e3ce-4ede-a018-ae32e0445584)

**Comment by andycochran** [comment]
Made irrelevant by #784.
