### ISSUE TITLE
Null dcpActualenddate for Final Letter Sent milestone causes Invalid Date to display on reviewed tab

### ISSUE THREAD

**Issue by godfreyyeung** [NYCPlanning/labs-zap-search#759]
Testing with staging data reveals that the "Final Letter Sent" milestone may have a null dcpActualstartdate value, causing the project card to say "Invalid Date"

![Screen Shot 2019-10-04 at 11.35.08 AM.png](https://images.zenhubusercontent.com/5ced7833554ce77a5db49edf/588fb73d-2c8b-4575-8dd2-a797b193b575)

![Screen Shot 2019-10-04 at 11.35.20 AM.png](https://images.zenhubusercontent.com/5ced7833554ce77a5db49edf/30456f90-a26f-4980-9716-3bdef9382ade)

**Comment by hannahkates** [comment]
I think the best solution for this may be to just exclude the "Final Letter Sent" milestone. I'll check with LUR and David to see if this is important to include.

**Comment by hannahkates** [comment]
This is a data problem. We don't need to build a workaround for it.
