### ISSUE TITLE
Limit and reorder milestones shown on "upcoming" tab

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#768]
We should only show:
- Very first milestone
- Last milestone to complete (of milestones that are of "completd" status which one was completed most recently)
- Remaining milestones leading up to the LUP's review (all milestones ordered by sequence number, grab all milestones after the last completed milestone's sequence number. of those, grab the LUP user's last LUP-related milestone's sequence number, and display _all_ milestones between and including the last completed & this sequence number).

First and last to complete can be separated by a vertical ellipsis (...)

**Comment by allthesignals** [comment]
Just Need some design clarity on this

**Comment by andycochran** [comment]
All milestones that have an actual end date (except the first and last of those) should be replaced by a link to the profile view where you can see all milestones. 

![image](https://user-images.githubusercontent.com/409279/66437900-1336d580-e9f9-11e9-97a1-277d57bda55e.png)

The Font Awesome icon used here is `ellipsis-v`. 

Markup would look something like… 

```
<li class="small-margin-bottom">
  <a class="text-tiny" href="#">
    {{fa-icon 'ellipsis-v' fixedWidth=true class="tiny-margin-right"}}
    view full timeline
  </a>
</li>
```

_* LUP milestones should never be filtered out. If a LUP milestone has an actual end date, the one before it should be visible._

**Comment by allthesignals** [comment]
Might need to pair on this one, confused about some of the terms and how they relate to the data itself
