### ISSUE TITLE
Combine BB and BP reviews when in-progress on "reviewed" tab

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#770]
Combine these two 20 days remaining displays into one. They will always have the same start and end date. It should say "Borough President & and Borough Board Review"
![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/0f840f08-9dae-4a4f-9ca8-62823fb0c017)

**Comment by allthesignals** [comment]
I _think_ this should be fine now that the view should be listing dispositions, because the template will reference the disposition's project's milestones to find this data.

**Comment by allthesignals** [comment]
see reviewed-project-card.hbs
