### ISSUE TITLE
Current milestone display issue on "reviewed"

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#774]
If the current milestone is one that doesn't have a multi-day review period, the template doesn't render anything in the middle of the "reviewed" project card. We need to figure out what else to show instead, or correct the milestone timeline alignment so it doesn't look as weird.

![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/211b1e33-fa37-4ea1-8e6b-34870a7a01d4)

**Comment by andycochran** [comment]
IDK why the template logic would have that middle column showing nothing. It should show the current milestone name, regardless of what type of milestone it is. The logic for the big day count and end date should not be dependent on the milestone having "a multi-day review period." It should just use the planned end date, and any active milestone will have a planned end date.

**Comment by hannahkates** [comment]
The trouble with this is that some milestones don't seem to have an "In Progress" state, so we don't have a simply way of knowing which one is in progress. One solution would be to query for the next milestone (based on sequence number) that hasn't started yet.
