### ISSUE TITLE
`dcpPublicstatusSimp` inconsistent between Mirage and CRM 

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-zap-search#790]
Working on #789 uncovered a bug where the markup is not getting the correct classes for project status. For example, the public status class in `show-project.php` is concatenated with `dcpPublicstatusSimp`. 

```
<span class="label dark-gray publicstatus-{{dasherize model.dcpPublicstatusSimp}}">{{model.dcpPublicstatusSimp}}</span>
```

The mirage data is using various formats which do not match what CRM will give us: 

![image.png](https://images.zenhubusercontent.com/5ca23880d9fcf5278d71596e/44385a8f-78ac-412a-92e0-ca12c282ec88)

CRM provides Title Case strings for `dcpPublicstatusSimp` which are used for display in the UI. So the mirage data gives us kebab-cased UI. 

![image.png](https://images.zenhubusercontent.com/5ca23880d9fcf5278d71596e/98e4bfac-14bb-4fa8-9be0-128d25be6eb8)

`dcpPublicstatusSimp` is also used for template/JS logic. For example… 

```
    if (this.tab === 'upcoming') {
      if (this.dcpPublicstatusSimp !== 'filed') {
        const participantMilestoneId = MILESTONE_ID_LOOKUP[this.dcpLupteammemberrole];
```

So when fixing the mirage data to be consistent w/ CRM, we need to make sure app logic doesn't break.

**Comment by godfreyyeung** [comment]
This was address through PR #800 / Issue #738
