### ISSUE TITLE
Visualize Past, Today, Future in milestones list

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zap-search#81]

**Comment by chriswhong** [comment]
Let's highlight "today" if the date for a milestone is today's.  Otherwise, let's visually distinguish between milestones the are completely in the past and completely in the future.

**Comment by andycochran** [comment]
New branch `milestones-past-and-future` has the start of this work.

**Comment by chriswhong** [comment]
TODO:
- visualize "today"
- confirm sort order so milestones appear chronologically

**Comment by andycochran** [comment]
Moved sort order task to separate issue (#168), as it may be a wontfix.
