### ISSUE TITLE
Opting out of hearings prevents submission of recommendation 

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-zap-search#810]
To reproduce: 
- go to My Projects / To Review
- opt out of hearings for a project
- click "Submit Community Board Recommendation"
- fill out a valid form
- click "Continue"

The modal is then broken, with no way to continue/cancel. 

![image.png](https://images.zenhubusercontent.com/5ca23880d9fcf5278d71596e/e087a21e-acab-457d-8324-485870e64ca2)

**Comment by hannahkates** [comment]
No longer an issue
