### ISSUE TITLE
Archive tab needs to handle invalid project completion dates

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#828]
Several projects on the archive tab on zap-staging-lupp have an invalid date for project completion. We should set up handling for this that says "Completion date unknown"

![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/a2d56869-b386-4375-84dc-ce0ea8c9f26a)

**Comment by andycochran** [comment]
Or just `<small class="light-gray">Date Unknown</small>` (no need to say "Completion").

**Comment by godfreyyeung** [comment]
Related to #823
