### ISSUE TITLE
Uploaded files aren't always listed

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#841]

**Comment by allthesignals** [comment]
Hmmm can clues on reproducing this? Which files did you try? I'll try to make a test...

**Comment by hannahkates** [comment]
It seems like the first time you upload a file, it doesn't show up. If you try again, it displays the name. So maybe it's not properly saving/registering the file name on the first upload.

**Comment by andycochran** [comment]
After a ton of manual testing, I'm able to replicate this. It's inconsistent, and I'm uncertain what's causing it. But I found a reliable indication of when the selected file(s) won't be listed. 

After clicking the "Choose Files" button, upon opening the browser's file picker, the file picker will sometimes (randomly?) go into a state where you can only select one file at a time. If the file picker is in this state and you choose a file, it will not be listed in our UI. 

If you _can_ select multiple files in the file picker, they will alway be listed in our UI (regardless of choosing one or multiple). 

I suspect that… 
- files that don't get listed in our UI aren't actually being selected
- this is a browser/file picker issue, and not a problem with our code

**Comment by andycochran** [comment]
Strike all of that. I figured it out. There was a stray extra `<input type="file">` in the markup. The inputs were sitting on top of each other in the layout. The bug is that if you click the edge of the button, you're clicking the hardcoded file input that isn't `multiple` or even hooked up to Ember. 

🤦‍♂️
