### ISSUE TITLE
"God mode" view for toggling between LUP users

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#843]
It would be really helpful if we had a way to login to ZAP as multiple different LUP users to see how their projects show up. This would be beneficial for
1. LUR's and Pipeline's data cleanup efforts
2. Usability testing and demos
3. Our development purposes, checking for display issues with real data from API
4. Future applicant portal work, for the same reasons above

**Comment by allthesignals** [comment]
Added a test suite which will let me move forward on necessary refactors
