### ISSUE TITLE
Load spinner between assignments tabs

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zap-search#864]
There should be a load spinner when moving between each assignment tab under my-projects

**Comment by andycochran** [comment]
+1! This is a great idea. It seems the route doesn't switch between tabs until the data has loaded. It'd be nice if clicking a tab instantly switched the route and showed a loading spinner until the data loaded.

**Comment by andycochran** [comment]
On zap-staging-lupp, some of the tabs are taking like 5 seconds to load, during which the user will assume their click didn't do anything because there's no feedback.
