### ISSUE TITLE
Fix nav bar before promoting to master

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#871]
With the LUP sign in option hidden, the nav bar looks weird and sparse. "Search" is the only option and it isn't clear what that means. We should make this easier to understand before we promote develop to master.

![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/336ca401-2a1a-4181-9e5d-fcaac4c0238c)

I like the old "Find Projects" prompt better 
![image](https://user-images.githubusercontent.com/13967925/67954592-99dd6d80-fbc7-11e9-8455-5d2ae7650efc.png)

**Comment by andycochran** [comment]
Closing this, as we've already deployed the new site header to prod. We should do usability testing to see if "Find Projects" is better than "Search."
