### ISSUE TITLE
Download data feature is broken on staging

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#878]
Trying to download a CSV file takes you to https://zap-api-staging.herokuapp.com/projects.csv?page=1&dcp_publicstatus%5B0%5D=Filed&dcp_publicstatus%5B1%5D=In%20Public%20Review

Trying to download a shapefiles file takes you to https://zap-api-staging.herokuapp.com/projects.shp?page=1&dcp_publicstatus%5B0%5D=Filed&dcp_publicstatus%5B1%5D=In%20Public%20Review

**Comment by trbmcginnis** [comment]
I think during the refactor, the download route was removed and never added back to the new version. So I think a fix for this would be to just recreate the download route `download.js` from `labs-zap-api` in `zap-api` using Nestjs

**Comment by allthesignals** [comment]
@hannahkates shapefiles are still not in there yet so idk if we can close yet
