### ISSUE TITLE
Hearing details aren't populating on hearing confirmation modal

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#889]
![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/c008ee9e-fcc7-414a-b3d2-aa2a484d8f76)

**Comment by allthesignals** [comment]
Confirming I'm seeing this on staging @trbmcginnis let me know if you want to pair on looking through this issue!
