### ISSUE TITLE
Show borough name, not number, in BBL tooltip

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zap-search#89]

**Comment by chriswhong** [comment]
![LabsApplicantMaps.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/580f65f4e41c721300d753c7/125516c66e82c728ace21e0d46c4959830a393b983e0bc42aa49dd953955653f6b14b1247a80e03cfd1839540d5e1bab135e0d40fef0df7eaeb63c71d90d03ef826c5766da2f53fde6d640e258f075c95d8fa4bd8346c1ed3f2ce28f8a463c1f02198eed10.png)

**Comment by andycochran** [comment]
This was working when I PR'd it. 🤔
