### ISSUE TITLE
Hearing details don't display after submission

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#890]
After submitting a hearing from the "upcoming" tab or "to review", the hearing details aren't displayed on the project card. The hearings also don't show up on the detailed project milestone list on the project profile. It seems like they're not actually getting saved to the model.

Related to #889

**Comment by allthesignals** [comment]
Related to #889

**Comment by trbmcginnis** [comment]
This issue was closed by PRs 1. https://github.com/NYCPlanning/labs-zap-search/pull/893 and 2. https://github.com/NYCPlanning/labs-zap-search/pull/906
