### ISSUE TITLE
sub-milestones not showing up when submitting a hearing in staging

### ISSUE THREAD

**Issue by trbmcginnis** [NYCPlanning/labs-zap-search#895]
sub-milestones are not showing up on tabs or on `show-project` page

**Comment by trbmcginnis** [comment]
- sub-milestones not showing up was happening because `dcp_recommendationsubmittedbyname` field had not been added to the API
- Most of `dcp_recommendationsubmittedbyname` values in the `dcp_communityboarddisposition` table in the database are NULL, which breaks the `hearings-list-for-milestones-list` component because this field is necessary for matching dispositions to particular milestones
- shelving this for now until we find a better solution

Possible solutions:  
- Solution option: make sure that this field is filled out consistently in the future
- Solution option: we can choose a different field to use for matching. We do have `dcp_recommendationsubmittedby` field which is a contact id that matches the `contactid` field in the `contact` table. We can map `dcp_recommendationsubmittedby` to the user's contactid and then grab the corresponding `landUseParticipant` value. Create a new computed property in disposition model that does this. Looks like we're not currently grabbing the `contactid` from the API for the frontend `user` model so will have to add that as well

**Comment by trbmcginnis** [comment]
Closing this because the refactor in #948 will fix it

**Comment by trbmcginnis** [comment]
Closing this because the refactor in #948 will fix it

**Comment by hannahkates** [comment]
This is still a problem. Hearings and recommendation submilestones aren't appears on the project profile.

**Comment by trbmcginnis** [comment]
Original fix: use the field `fullname` from the contact table as a replacement for `dcp_recommendationsubmittedbyname`

Now we're encountering data issues:

In order for the hearings data to show up on the sub-milestones, `dcpPublichearinglocation` and `dcpDateofpublichearing` fields are required.

In order for recommendation data to show up on the sub-milestones, `dcpDateofvote`, `dcpVotinginfavorrecommendation`, `dcpVotingagainstrecommendation`, `dcpVotingabstainingonrecommendation`, and one of the recommendation fields (e.g. `dcpCommunityboarddisposition`) are required. 

It looks like even when the `statuscode` for a project is `1`, which means the recommendation has been submitted and each of these above required fields SHOULD be filled, the data shows that there are still a lot of NULL values.

**Comment by trbmcginnis** [comment]
An Example project: https://zap-staging-lupp.planninglabs.nyc/projects/P2016Q0306

While all of the data seems to be correct in the database ( all of the required fields are populated ), Ember Data isn't showing a lot of this data when I look at the staging site.

For looking up this data in the database:

```SELECT 
dcp_project,
contact.fullname,
dcp_project.dcp_name,
dcp_publichearinglocation,
dcp_dateofpublichearing,
dcp_communityboardrecommendation,
dcp_boroughboardrecommendation,
dcp_boroughpresidentrecommendation,
dcp_dateofvote,
dcp_votinginfavorrecommendation,
dcp_votingagainstrecommendation,
dcp_votingabstainingonrecommendation
FROM dcp_communityboarddisposition 
LEFT JOIN dcp_project ON dcp_projectid = dcp_project 
LEFT JOIN contact ON dcp_recommendationsubmittedby = contact.contactid
WHERE dcp_communityboarddisposition.statuscode = 'Submitted'```

**Comment by trbmcginnis** [comment]
Fixed by adding `fullname` as a key to `disposition.entity.ts`
