### ISSUE TITLE
Can't opt out of hearings on the Upcoming tab 

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-zap-search#900]
If you go to the Upcoming tab and click "Opt Out" then confirm "Opt Out" again in the modal, the modal closes, but nothing changes in the project UI — you still see the post/opt-out buttons.

**Comment by andycochran** [comment]
`hearingsWaived` isn't getting updated on the assignments model.

**Comment by andycochran** [comment]
@trbmcginnis Can you maybe take a look at this one?

**Comment by allthesignals** [comment]
I think this was fxied but let's double check
