### ISSUE TITLE
Is there a character limit for LUP form fields?

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#914]
Check that CRM doesn't have a character limit on the rec comments. If it does, we need to implement a limit in the front-end.

**Comment by andycochran** [comment]
Same for all form fields.

**Comment by allthesignals** [comment]
what's the status with this?

**Comment by trbmcginnis** [comment]
@allthesignals Going to work on it today

**Comment by trbmcginnis** [comment]
From https://dcppfsuat2.crm9.dynamics.com/

ULURP Number: 12
CEQR Number: 11
Docket Description: 2000
Public Hearing Location: 100
Name of Person Completing Form: 50
Title: 50
Consideration: 2000
Vote Location: 100
