### ISSUE TITLE
Update build-url helper to use online ZR

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#925]
We use a helper to generate the URLs provided for zoning actions on the project profiles. The helper assumes we should send the user to DCP's website. We should update the helper to use the new online ZR instead. However, we need more info about the online ZR URL structures and linking before we can do this

https://github.com/NYCPlanning/labs-zap-search/blob/develop/app/helpers/build-url.js

Screenshot of where links are provided on project profile:
![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/3e4e76d3-4d19-4135-900b-9fee2d8af6c4)

**Comment by andycochran** [comment]
Here's an example of deep-linking to sections of the online Zoning Resolution site: 

https://zr.planning.nyc.gov/article-iii/chapter-3#33-012
