### ISSUE TITLE
End-to-end testing of file uploads

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#926]

**Comment by allthesignals** [comment]
@godfreyyeung how's this going? I'm going to keep trying a few things as well...

**Comment by allthesignals** [comment]
@godfreyyeung Most changes should be deployed rn can you check on this?

**Comment by godfreyyeung** [comment]
@allthesignals I finally found a multi-dispo assignment on staging that let me submit it. 
The assignment had two dispositions and I uploaded two files, resulting in four POST requests.
All but one POST request succeeded, thus preventing a successful submission. Details:

- Project: https://zap-staging-lupp.planninglabs.nyc/projects/P2017K0431
- Assignment ID: 15ac2042-970b-ea11-a9aa-001dd8308025
- Disposition “P2017K0431 - ZM - QN BP”  successfully received  both files
   - uploadTest3.txt 
   - uploadTest4.txt
- Disposition "P2017K0431 - ZR - QN BP"  only received one file
   -  uploadTest3.txt only

The failed POST request's response was a 500 internal server error:
```
* Request URL: https://zap-api-staging.herokuapp.com/document
* Request Method: POST
* Status Code: 500 Internal Server Error
* instanceId: cb0f8340-970b-ea11-a99d-001dd830809a
* entityName: dcp_communityboarddisposition
* Content-Type: text/plain
* file: (binary)
```
Definitely would be nice to have a test DB to have better repeated tests for this.

**Comment by allthesignals** [comment]
@godfreyyeung great catch! I'll sift through the logs...

**Comment by godfreyyeung** [comment]
@allthesignals Looking at the logs, it looks like it is because the failed disposition's `dcp_name` is undefined in CRM

**Comment by godfreyyeung** [comment]
Actually, that is odd.. why would `dcp_name` be defined for the disposition for one file but not  the other?

**Comment by godfreyyeung** [comment]
I'm going to try debugging this locally, too

**Comment by godfreyyeung** [comment]
Unable to reproduce now without a reliable way to get multi-dispo projects. Will table for now.
