### ISSUE TITLE
Test login as a real user (without redirect)

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#927]

**Comment by allthesignals** [comment]
@hannahkates how should we test this? Do we have access to the accounts? I remember a list of accounts somewhere.

**Comment by hannahkates** [comment]
@allthesignals We'll need someone to give us ownership of the contact records. Once we have ownership, in CRM we can set the LUP contact's email to our own and login via NYC.ID using our own credentials.

**Comment by hannahkates** [comment]
The QA team is doing this.
