### ISSUE TITLE
On the Public hearing record, the refresh button/reload does not work

### ISSUE THREAD

**Issue by gopal2020** [NYCPlanning/labs-zap-search#931]
Browser: Chrome
Project name:130-24 South Conduit Ave Self Storage ULURP
Expected Result: On the Public hearing record, the refresh button/reload should work
Actual Result: On the Public hearing record, the refresh button/reload does not work

Please see screenshot

![lup bug1](https://user-images.githubusercontent.com/57265341/68885168-a04d0880-06e2-11ea-8b53-cde29bd6997c.PNG)

**Comment by gopal2020** [comment]
Triage: @andycochran will investigate.

**Comment by hannahkates** [comment]
Refresh should take you back to my-projects

**Comment by andycochran** [comment]
@godfreyyeung Could you take a look at this one? Here's what we want to do… 

The problem is that if you refresh an `add` view (or load it directly) the app doesn't have the data model it needs to render the view. So when this error happens, we should have an error action redirect the user back to `my-projects/to-review`. This error action should be on both the add recommendation and add hearing views.

**Comment by godfreyyeung** [comment]
@andycochran  Yep, I'll take a look at this one. Sorry, I gotta check my GitHub notifications

**Comment by andycochran** [comment]
Why do we need to verify the hearings state? Seems like we should be able to just send the user to `my-projects` if `recommendations/add` or `hearing/add` doesn't have the data it needs in memory. @allthesignals, do you have any advice on how we solve this?

**Comment by allthesignals** [comment]
@godfreyyeung yeah, hmm I don't follow why that is.

One way to solve this is to add an error action handler in the route. 

I'll just take a look at this... how about you continue focus on doc upload issues?

**Comment by allthesignals** [comment]
Fixed this here: 354e66ee75fafe95d1deffb76f9334f3bb1f2b2c

It now redirects to `my-projects`.

In the future we should definitely just add the correct endpoint for this.

**Comment by hannahkates** [comment]
This bug is resolved. QA Team please review.

**Comment by ksinghprod** [comment]
This issue is now fixed 

![image](https://user-images.githubusercontent.com/57362229/69573288-ccdf0b00-0f93-11ea-8db5-178c2aea9ce7.png)
