### ISSUE TITLE
recommendation power-select filtering errors

### ISSUE THREAD

**Issue by godfreyyeung** [NYCPlanning/labs-zap-search#936]
Filtering on the recommendation power-select is erroring, complaining about needing a searchField value

**Comment by allthesignals** [comment]
This refers to typeahead filtering which requires a searchField param.

Here's how to reproduce:

Click a rec outcome dropdown, start typing ahead, see error.

![Screen Shot 2019-11-15 at 2.54.02 PM.png](https://images.zenhubusercontent.com/5ca23922d9fcf5278d715977/0c6fe6d4-84cc-4209-83b0-35f9e70a1967)
