### ISSUE TITLE
Hearing details don't show up on the upcoming tab

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#940]
If you submit a hearing for a project on the upcoming tab, the button disappears as expected, but the hearing date/locations details aren't displayed on the project card. They should show up they same way they do on the "to review" tab.

**Comment by trbmcginnis** [comment]
The hearing details are actually not supposed to show up the same way on the "upcoming" tab as they do on the "to-review" tab, instead they will show up as a sub-milestone within the milestones list. There is currently no UI to display them on the project card elsewhere.

Closing this ticket
