### ISSUE TITLE
Get NYC ID set up for prod

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#946]
nycidintegration <nycidintegration@doitt.nyc.gov>

**Comment by allthesignals** [comment]
I think this depends on security accreditation

**Comment by allthesignals** [comment]
Going to submit request

**Comment by allthesignals** [comment]
Submitted req today, waiting for response

**Comment by allthesignals** [comment]
Waiting for follow up from the citywide desk help

**Comment by allthesignals** [comment]
This is completed
