### ISSUE TITLE
Refactor sub-milestones

### ISSUE THREAD

**Issue by trbmcginnis** [NYCPlanning/labs-zap-search#948]
Do a LEFT JOIN in the backend `dcp_communityboarddisposition.dcp_recommendationsubmittedby` and `contact.fullname` so that we have access to the fullname field on each disposition. This field will take the place of `dcp_recommendationsubmittedbyname` since many of the rows in this field are NULL. 

~Show list of hearings for a project. If participant type information is available, display it. ~At the ~moment we cannot link hearing dispos to milestones, so we will show them separately. ~@andycochran please advise a design workaround for this...~ @hannahkates found a way to do this!~

~One missing piece is `dcpRecommendationsubmittedbyname`. Is it being filled in by the hearing submission form? We should make sure this happens. ~

~That said, we think we should still do these things in the future, data quality permitting.~

~Enhancements:~

- ~No longer use disposition model field `dcpRecommendationsubmittedbyname` because a lot of its values are NULL~
- ~Create a model relationship between milestones and dispositions? One milestone will have many dispositions~

**Comment by hannahkates** [comment]
Hmm @trbmcginnis thinking about this more, I'm not sure if it'll work. For the submilestones, we want ALL the submilestones for all LUPs on a given project. The computer value on the assignment model is dependent on the specific user that's logged in. There may be another way around this, but I don't think we can use assignment.

**Comment by trbmcginnis** [comment]
@hannahkates Yeah realized this too :/, we're thinking about doing a model relationship between milestones and dispositions

**Comment by trbmcginnis** [comment]
SELECT disp.dcp_recommendationsubmittedby, contact.fullname FROM dcp_communityboarddisposition AS disp
LEFT JOIN contact ON dcp_recommendationsubmittedby = contact.contactid
