### ISSUE TITLE
Stage: Recommendation submitted date displaying in CRM but on LUP portal NOT displaying 

### ISSUE THREAD

**Issue by gopal2020** [NYCPlanning/labs-zap-search#952]
Browser: Chrome
Project Name:  Peninsula Hospital Redevelopment Plan

Actual Result: Recommendation submitted date displaying in CRM but on LUP portal NOT displaying 

Expected Result: Recommendation submitted date should display in CRM and  LUP portal 

![ss1](https://user-images.githubusercontent.com/57265341/69057062-3339bb80-09df-11ea-8675-898897014031.PNG)
![ss2](https://user-images.githubusercontent.com/57265341/69057345-ad6a4000-09df-11ea-8cdf-453aac6e006b.PNG)

**Comment by gopal2020** [comment]
Triage: Lab team will Investigate.

@hannahkates

**Comment by trbmcginnis** [comment]
Has to do with `assignment.toReviewMilestonePlannedCompletionDate` on `reviewed-project-card`

**Comment by trbmcginnis** [comment]
![Screen Shot 2019-11-20 at 5.05.44 PM.png](https://images.zenhubusercontent.com/5ca36b1555cfe32f2f66b411/d576119b-c8d3-4541-8a89-7a98e1d43cc9)

**Comment by allthesignals** [comment]
@trbmcginnis if you suspect a data issue punt it over my way or lemme know if i can help!

**Comment by trbmcginnis** [comment]
![Screen Shot 2019-11-21 at 10.29.42 AM.png](https://images.zenhubusercontent.com/5ca36b1555cfe32f2f66b411/30e5736c-2588-4160-a10d-021f6aa77292)

**Comment by trbmcginnis** [comment]
Update:

I originally assumed that `dcpDatereceived` would be calculated to equal the date that the LUP submitted their recommendation in the portal but now I'm not seeing a calculation like this in the frontend or the backend so I'm curious how `dcpDatereceived` is actually being calculated at all? Is it calculated in CRM?

**Comment by ksinghprod** [comment]
This issue is now fixed 

![image](https://user-images.githubusercontent.com/57362229/69980012-614dee00-14fd-11ea-9353-bf13c0953d93.png)
