### ISSUE TITLE
On staging, action name/number does not show on recommendation by action

### ISSUE THREAD

**Issue by godfreyyeung** [NYCPlanning/labs-zap-search#953]
On the recommendation by-action form, the action name and number is not showing even though `action.dcpName` has a value:

![Screen Shot 2019-11-18 at 11.02.17 AM.png](https://images.zenhubusercontent.com/5ced7833554ce77a5db49edf/4de2f60f-22bf-4e84-a9c0-aa2f55f0f822)

**Comment by hannahkates** [comment]
@godfreyyeung this should be fixed already by the serialization PR. matt and i will be checking today to make sure it fixed the problem.

**Comment by trbmcginnis** [comment]
Closing and combining into #976
