### ISSUE TITLE
Stage: Project/Disposition is not displaying in LUP Portal

### ISSUE THREAD

**Issue by gopal2020** [NYCPlanning/labs-zap-search#956]
Project Name: Happy Halloween

Actual Result: Project/Disposition is not displaying in LUP Portal.
Expected Result: Project/Disposition should display in LUP Portal.

Waiting time 4 hours.

![image](https://user-images.githubusercontent.com/57265341/69094281-12dd2180-0a1e-11ea-9cf8-25b21df16233.png)

![image](https://user-images.githubusercontent.com/57265341/69093848-4f5c4d80-0a1d-11ea-8146-23bee9360488.png)

**Comment by gopal2020** [comment]
Its not a BUG. It is working fine.

**Comment by ksinghprod** [comment]
This issue is now fixed
