### ISSUE TITLE
Stage: Inactive Recommendations' information is appearing under the "was a quorum Present at your hearing(s)?" section on the LUP portal 

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-zap-search#957]
Browser: Chrome
Project name: Peninsula Hospital Redevelopment Plan

Expected Result: Only Active Recommendations' information should appear under the  "was a quorum Present at your hearing(s)?" section 

Actual Result: Inactive Recommendations' information is appearing under the "was a quorum Present at your hearing(s)?" section on the LUP portal 

In the screenshot, you can see that only one BP disposition is active

![image](https://user-images.githubusercontent.com/57362229/69093589-be857200-0a1c-11ea-8230-6a5e419710f4.png)

![image](https://user-images.githubusercontent.com/57362229/69093651-db21aa00-0a1c-11ea-8826-eac4f6e4389f.png)

**Comment by andycochran** [comment]
Related to #935

**Comment by hannahkates** [comment]
This doesn't seem to be an issue anymore with the newly cloned data from production. My guess is that it was a temporary data issue. The dispositions for Peninsula Hospital Redevelopment Plan are all Submitted/Inactive and the project shows up on the Reviewed tab, not To Review.

**Comment by ksinghprod** [comment]
This issue is now fixed
