### ISSUE TITLE
Stage: LUP is getting the option to submit multiple recommendations for dispositions that have only one active disposition 

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-zap-search#958]
Browser: Chrome

Project: Peninsula Hospital Redevelopment Plan

Expected Result: User should not receive the option to submit multiple recommendations, if there is only one recommendation to submit  

Actual result: User is receiving the option to submit multiple recommendations for projects/actions that have only one hearing 

![image](https://user-images.githubusercontent.com/57362229/69095217-dd393800-0a1f-11ea-8573-262c57b2d0ac.png)

![image](https://user-images.githubusercontent.com/57362229/69095293-ffcb5100-0a1f-11ea-9c2a-060b884216c8.png)

**Comment by andycochran** [comment]
Likely related to #935, dispostions showing when deactivated.

**Comment by andycochran** [comment]
Since #935 was closed, is this issue still valid?

**Comment by andycochran** [comment]
This line in the query makes sure that we're only using active disposition:

```
AND statuscode = 'Active' -- only want lup project assignments that haven't been deactivated
``` 

https://github.com/NYCPlanning/zap-api/blob/00d3829bf27934a8130e207dfae2d7f403c700af/queries/assignments/index.sql#L12 

So I'm not sure what else could be causing a project with a single disposition to allow submission of multiple recommendations. I think we need to try reproducing this bug.

**Comment by hannahkates** [comment]
This appears to be a data issue where DCP staff filled in real dispo data for all but one of QN BP the dispositions. I don't know if we should build a workaround for this. Our app will always be sending data to all dispositions records at the same time, so this should never be as issue for projects where LUPs are using our app to submit. This problem will only arise with human error when DCP fill in dispositions on behalf of LUPs.

![image](https://user-images.githubusercontent.com/13967925/69568179-1fff9080-0f89-11ea-99c4-d52e4a976d5f.png)

**Comment by ksinghprod** [comment]
This is not an issue anymore 

![image](https://user-images.githubusercontent.com/57362229/70088427-38545880-15e4-11ea-9c4e-60a2dfa52ab8.png)
