### ISSUE TITLE
Stage: LUP is not able to click/view/delete files he/she uploads prior to submission of recommendation 

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-zap-search#960]
Browser: Chrome

Project name: Queens Blvd MIH Text Amendment 

Expected Result: LUP should be able to click on/view/edit/delete files that he/she uploads to the recommendation, prior to the submission 

Actual Result: LUP is not able to click/view/delete files he/she uploads prior to submission of recommendation 

![image](https://user-images.githubusercontent.com/57362229/69096269-15417a80-0a22-11ea-9f67-0434df9666e2.png)

![image](https://user-images.githubusercontent.com/57362229/69096329-30ac8580-0a22-11ea-96e4-fc4829a02be4.png)

**Comment by andycochran** [comment]
We'll add X buttons next to file list items to remove them from the files that will be uploaded.

**Comment by godfreyyeung** [comment]
@andycochran I can add the functionality for this.

**Comment by hannahkates** [comment]
This bug is resolved. QA Team please review.

**Comment by ksinghprod** [comment]
This issue is fixed, we can now delete the file we upload

![image](https://user-images.githubusercontent.com/57362229/69575299-fa2db800-0f97-11ea-835a-1ec2e28b1577.png)
