### ISSUE TITLE
Stage: LUP is unable to submit a Recommendation 

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-zap-search#961]
Browser: Chrome

Project Name: Queens Blvd MIH Text Amendment 

Expected Result: LUP should be able to a recommendation (whether he/she attaches documents or not) 
Actual Result: LUP is unable to submit a Recommendation 

Note: I added a two files to this recommendation, one of them being a test virus. I am not certain is the virus has something to do with it, but I did not see an upon to remove/delete files 

![image](https://user-images.githubusercontent.com/57362229/69096453-7701e480-0a22-11ea-8882-8d7e8e6b5498.png)

**Comment by andycochran** [comment]
QA to provide upload files to Labs so we can reproduce this issue.

**Comment by andycochran** [comment]
Suspicion: 2000-char limit on rec field?

**Comment by allthesignals** [comment]
We recreated the bug just by submitting a rec with the information above... when it tries to hit the /document endpoint, it throws an unauthorized:

{"statusCode":401,"message":"Unauthorized"}

This might have to do with some last minute auth steps.

**Comment by allthesignals** [comment]
I think the issue has to do with how the document is being uploaded.

Normally all requests should include the following ajax configuration:

```
hash.xhrFields = { withCredentials: true };
```

This allows the http-only cookie to be sent. I'll investigate

**Comment by allthesignals** [comment]
@gopal2020 fix for this was deployed, feel free to give it a try on a project.

**Comment by ksinghprod** [comment]
This issue is now fixed 

![image](https://user-images.githubusercontent.com/57362229/70085516-5e76fa00-15de-11ea-8d3b-43da372b9909.png)


![image](https://user-images.githubusercontent.com/57362229/70085534-68006200-15de-11ea-9fa4-e184c28eebc5.png)
