### ISSUE TITLE
Stage: Documents that were uploaded to one project are carrying over to other projects (on the recommendation section) 

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-zap-search#962]
Browser: Chrome

Projects: 147-40 15th Ave Commercial Overlay Rezoning 
               Queens Blvd MIH Text Amendment

Expected Result: Documents uploaded to a certain recommendation/project should only appear on that record

Actual Result:  Documents that were uploaded to one project are carrying over to other projects (on the recommendation section) 

![image](https://user-images.githubusercontent.com/57362229/69096902-6736d000-0a23-11ea-833b-767c058a4cf6.png)

I uploaded these two files on this project 
![image](https://user-images.githubusercontent.com/57362229/69096954-803f8100-0a23-11ea-8e05-668bf4578d60.png)

But they are also showing up on the 

Queens Blvd MIH Text Amendment Project

**Comment by andycochran** [comment]
Components should be destroyed and re-initiated when viewing subsequent /add views.

**Comment by allthesignals** [comment]
I think this is because `fileQueue` is a service on the controller (both singletons), so they won't get wiped out across transitions.

**Comment by godfreyyeung** [comment]
@allthesignals @andycochran  I can write a patch to flush all queues upon load of `recommendations/add.js`

**Comment by allthesignals** [comment]
@godfreyyeung sure, I had some work on this, but if you know a quick way lemme know. I had trouble implementing my patch.

**Comment by allthesignals** [comment]
@godfreyyeung just go for it! thanks

**Comment by allthesignals** [comment]
Taking another look at this.

**Comment by hannahkates** [comment]
This bug is resolved. QA Team please review.

**Comment by gopal2020** [comment]
This bug is fixed.

![image](https://user-images.githubusercontent.com/57265341/70179184-99932f00-16ab-11ea-8677-8c2631ed3f5a.png)

**Comment by allthesignals** [comment]
YESSSSS

**Comment by allthesignals** [comment]
Major kudos to @godfreyyeung for fixing
