### ISSUE TITLE
Milestones that repeat aren't getting tagged as "Revised"

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#966]
Example:
https://zap-staging-lupp.planninglabs.nyc/projects/P2015K0272

This project has multiple land use application filing milestones. The front-end is supposed to detect that there are multiple and label all of them that occur after the initial one as "Revised Land Use Application Filed". ~It seems like the front-end check for that broke. There are a few milestones it should be adding "Revised" to when there are multiple. I think those checks are all in one component.~ 

EDIT: The new API does not return the needed `isRevised` boolean.

**Comment by andycochran** [comment]
Was gonna fix. But it's not a problem with the front end. The new API does not return a `isRevised` boolean. I've unassigned, since there's milestone logic sprinkled thru the API and someone better with queries should probably look at this.
