### ISSUE TITLE
Stage: A Project Under the Upcoming tab is displaying, the public hearing date

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-zap-search#970]
Browser: Chrome

Project ID: 52nd Street Rezoning 

Expected Result: Under the To Review tab, LUP should only see the project's information and the public hearing option. 
Actual Result: Under the To Review tab, LUP is able to see the public hearing date 

![image](https://user-images.githubusercontent.com/57362229/69272618-e6074680-0ba4-11ea-8a31-942f11bc0742.png)

**Comment by ksinghprod** [comment]
Browser: Chrome

Project ID: 52nd Street Rezoning 

Expected Result: Under the To Review tab, LUP should only see the project's information and the public hearing option. 
Actual Result: Under the To Review tab, LUP is able to see the public hearing date

**Comment by gopal2020** [comment]
Triage: As design

**Comment by hannahkates** [comment]
Yes, this should be here, but it is ugly. @andycochran can you come up with a nicer way to display this info when it's available?

**Comment by andycochran** [comment]
It's displayed here just like it's displayed in other tabs. Is there something particularly ugly about it? It might just look weird out of context of the milestones/timeline. Once we bring that back it will look better.

**Comment by gopal2020** [comment]
Triage: As Design.
