### ISSUE TITLE
Stage: View Full Project Timeline link does not work

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-zap-search#971]
Browser: Chrome
Project ID: 20th Avenue Elimination - Queens

Expected Result: LUP should be able to able to click on the View Full Project Timeline link and the Project timeline should appear

Actual Result: View Full Project Timeline link does not work

![image](https://user-images.githubusercontent.com/57362229/69273484-71350c00-0ba6-11ea-8686-80a3b18c96cc.png)

**Comment by andycochran** [comment]
I'll fix this.

**Comment by gopal2020** [comment]
It is fixed

**Comment by ksinghprod** [comment]
![image](https://user-images.githubusercontent.com/57362229/70176307-436fbd00-16a6-11ea-95e1-ef78d5e049ce.png)
