### ISSUE TITLE
Stage: A Project/disposition is appearing on the LUP portal that does not have a QN BP account associated to the LUP team 

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-zap-search#972]
Browser: Chrome

Project Name: 2513-2523 Avenue O Rezoning

Expected Result: Only Projects that are associated to the QN BP LUP account should show up under the to review tab on the LUP portal

Actual Result: A Project/disposition is appearing on the LUP portal that does not have a QN BP account associated to the LUP team 

![image](https://user-images.githubusercontent.com/57362229/69277029-86616900-0bad-11ea-944c-0639ab72f5d6.png)

![image](https://user-images.githubusercontent.com/57362229/69277111-ac870900-0bad-11ea-8e75-d0315c34e339.png)

![image](https://user-images.githubusercontent.com/57362229/69277179-ce808b80-0bad-11ea-92f7-33878cf9ca19.png)

**Comment by andycochran** [comment]
Need to investigate and double check the query.

**Comment by hannahkates** [comment]
I think this may have been a temporary data issue. The "2513-2523 Avenue O Rezoning" project is no longer showing up on any of the QN BP tabs.

**Comment by ksinghprod** [comment]
This issue is fixed, I am only seeing my projects on the Portal
