### ISSUE TITLE
Stage: On LUP Portal real user account Project/Disposition is  not displaying.  

### ISSUE THREAD

**Issue by gopal2020** [NYCPlanning/labs-zap-search#977]
Project name: Smoketesting11/08/2019

Actual Result: On LUP Portal real user account Project/Disposition is  not displaying.  
Expected Result:  Project/Disposition should display on LUP Portal real user account 

![image](https://user-images.githubusercontent.com/57265341/69366583-a6a02f00-0c64-11ea-89f7-01ccb53086f4.png)

![image](https://user-images.githubusercontent.com/57265341/69366372-3beef380-0c64-11ea-85c2-6401fd0d04e1.png)

![image](https://user-images.githubusercontent.com/57265341/69366456-693ba180-0c64-11ea-9989-5bd8d39eac26.png)

![image](https://user-images.githubusercontent.com/57265341/69366547-96884f80-0c64-11ea-8cc0-533e4377dba5.png)

**Comment by allthesignals** [comment]
Hi, 

One thing that makes this hard to debug is the # of "gchandrausdcp@gmail.com"s in the system. Can we make sure there's one and only one gchandrausdcp@gmail.com assigned to this? That way we can debug more easily.

I suspect this has something to do with the visibility of dispositions being "LUP" and not "General Public".

@hannahkates any thoughts?

**Comment by allthesignals** [comment]
I can't figure out why this project isn't appearing. Only difference I see is Gopal's project is largely ZM stuff.

**Comment by hannahkates** [comment]
@gopal2020 The project public status needs to be filled in. The project will appear in our portal once the project is "Filed"

[SQL for reference](https://github.com/NYCPlanning/zap-api/blob/develop/queries/assignments/index.sql#L77). It lists out the public statuses that correspond to different tabs in our app.

![image](https://user-images.githubusercontent.com/13967925/69550679-6e9d3280-0f69-11ea-909e-f0ca83e04bea.png)

**Comment by allthesignals** [comment]
@hannahkates I don't think this is closed yet... I cannot for the life of me get it to appear

**Comment by allthesignals** [comment]
(specifically this project)

**Comment by gopal2020** [comment]
This Issue  still open.  Project disposition not displaying in LUP portal.
email ID: gchandrausdcp@gmail.com
Project Name: Smoke testing11/08/2019

![image](https://user-images.githubusercontent.com/57265341/69657472-46383580-1048-11ea-89d7-88a860460161.png)

![image](https://user-images.githubusercontent.com/57265341/69657367-125d1000-1048-11ea-9596-41139bc69104.png)

![image](https://user-images.githubusercontent.com/57265341/69657150-cf02a180-1047-11ea-961e-30b837ea15f2.png)

![image](https://user-images.githubusercontent.com/57265341/69657115-bb573b00-1047-11ea-96e6-0d215c8cdc6d.png)

**Comment by gopal2020** [comment]
It is fix in staging Environment
![image](https://user-images.githubusercontent.com/57265341/69738476-28300b00-1104-11ea-9f6d-e3fb695f8c07.png)
