### ISSUE TITLE
Stage: User not able to complete submission of CB Disposition from LUP to CRM

### ISSUE THREAD

**Issue by gopal2020** [NYCPlanning/labs-zap-search#981]
Project Name: 1559-1563 Prospect Place, Weeksville.

Actual Result: User not able to complete submission of CB Disposition from LUP to CRM
Expected Result:  User should able to complete submission of CB Disposition from LUP to CRM

![image](https://user-images.githubusercontent.com/57265341/69375553-998c3b80-0c76-11ea-8c46-956d5c46f30c.png)

**Comment by andycochran** [comment]
Resolving #982 may fix this.

**Comment by gopal2020** [comment]
It is Fixed.

![image](https://user-images.githubusercontent.com/57265341/69758365-5413b680-112d-11ea-8346-03f07fa5a804.png)
