### ISSUE TITLE
Stage: Required Field Is not missing on LUP Portal Community Board form.

### ISSUE THREAD

**Issue by gopal2020** [NYCPlanning/labs-zap-search#982]
![image](https://user-images.githubusercontent.com/57265341/69377594-98f5a400-0c7a-11ea-8767-c2d92c717624.png)

**Comment by andycochran** [comment]
Required field does not prevent portal from submitting data, but the absence of the name fields breaks CRM workflows. We should get the LUPs name form the API and submit that with the record. We do not need to add a name field to the portal form (this can be a future enhancement if planners decide they need LUPs to be able to submit misc names from one account).

**Comment by hannahkates** [comment]
I think this fix has been implemented already. Let's confirm today.

**Comment by allthesignals** [comment]
@gopal2020 can you check this out again? Our forms are filling in the text "DCP" to make CRM validations happy. We can have it infer current user later down the road.

**Comment by hannahkates** [comment]
This bug is resolved. QA Team please review.

**Comment by gopal2020** [comment]
This bud is Fixed

![image](https://user-images.githubusercontent.com/57265341/69990197-3b334880-1513-11ea-8750-ec26a50c4074.png)
