### ISSUE TITLE
CRM and postgresql db are using different time zones

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#984]
This has come up a few times where timestamps don't match up. We need to figure out what timezone CRM is using and make sure our database uses the same

**Comment by andycochran** [comment]
This may actually not be a problem. Partner suspects fixing #982 will resolve the issues the time different causes.

**Comment by allthesignals** [comment]
I think this is a problem... but proposed solution here should close it: https://github.com/NYCPlanning/zap-api/pull/51

**Comment by hannahkates** [comment]
This bug is resolved. QA Team please review.

@ksinghprod
